### ISSUE TITLE
/search always displays "logged in"

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#1]
Navigating to:

* https://www.clas-digital.uni-frankfurt.de/search

always shows "Logged in" in the top-right, even when the search user is not logged in.

Ideally the Logged in options and text box should reflect the actual login status.

**Comment by sladen** [comment]
Console log from browser in question:

```
SyntaxError: missing ; before statement search:357:7
SyntaxError: missing ; before statement search:1046:9
SyntaxError: missing ; before statement search:1134:4
ReferenceError: ExecuteInitialise is not defined search:1:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. search
```
and after pressing *Search*:

```
ReferenceError: sendToPage is not defined search:1:0
```

**Comment by georgbuechner** [comment]
Feel free to reopen with screenshot/ url.
