### ISSUE TITLE
New Search Options: functionality  "From" and "After"

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#101]
The new setup of the search options (#77) has the options "from" and "after" which I dont think are understandable without further explanation.

Also, as the preset for "before" is "0", all searches return zero results, until one changes this setting (there arent any books published before the year 1 nach Christus...) 

This makes the search currently unusable.

I urgently suggest to take this update back/this option out until a good solution has been found.

**Comment by ekoehring** [comment]
Suggested solution:

 "published after" and "published before", with the auto-filled in numbers being not "0" but "void" (so that the option is not activated unless numbers are being filled in

**Comment by ekoehring** [comment]
More ideas: 
-- For filling them in, it would help to have hints like "year" and "name" in these fields.
-- The possibility to click years up and down is not needed, I think, and it would make the searchbar look less crowded if we got rid of them

**Comment by sladen** [comment]
Perhaps, until a good UI solution is worked out, the time drop down should be:

1. **Any time**
2. 1700s
3. 1800s
4. 1900s
5. 2000s

In the URL these can still be encoded as `from=YYYY` and `until=YYYY` which will allow an advanced user to manually edit the URL for a *very* specific query (eg. `&from=1850&until&1860`).

This is hopefully a good promise between usability, screen estate, development speed and retaining the back-end search as required.

**Comment by ekoehring** [comment]
Google Books uses a similar option to the one @sladen suggests, so many users might already be familiar with it. However, they have "custom range" as aditional option, which then opens a modal to define a range - in the long run, we do need the possibility to search "&from=1850&until&1860".
But for the moment, I think the dropdown described by Paul is a good solution.

**Comment by sladen** [comment]
Looking also at what Gmail (advanced search) does:

* https://support.google.com/mail/answer/7190

`after:` and `before:` for date ranges (`from:` is used for *author*).  So "Any time" would be encoded by having blank/empty (therefore not shown) `after=&before=`; and "1800s" would be encoded by having `after=1700&before=1800`.

For future-proofing, ISO8601 dates in the following formats should be accepted:

1. YYYY
2. YYYY-mm
3. YYYY-mm-dd

**Comment by sladen** [comment]
Eh... "1700s" would be encoded as `after=1700&before=1799`; where `after=` is the earliest date (1700-01-01 00:00) and and `before=` is the latest date (1799-12-31 23:59).

**Comment by georgbuechner** [comment]
I implemented a change, now saying after __ and before __ this is the same option as has been before. The default value (0, 0) won't be accepted till changed. So no worries about before being 0 as default. Is this an accapatable solution?

**Comment by sladen** [comment]
Perhaps this would work in the short-term?

    <input id='PublicatedAfter' type='number' step='50' value='1700'>";
    <input id='PublicatedBefore' type='number' step='50' value='2049'>";

**Comment by ekoehring** [comment]
In testing this, #91 becomes quite obvious (and confusing): the dropdowns/options do not reflect what i did, even though it is reflected in the URL and results. So when I do this search
https://www.clas-digital.uni-frankfurt.de/search?q=schwein&author=Buffon&publicatedafter=1770
The options bar does not tell me anymore that I filtered for books by Buffon, after 1770.
The options I chose should always be visible on the page, so that when I return to them 5 minutes later, I remember that/how I filtered!

**Comment by ekoehring** [comment]
In terms of the preset 0,0 for publicated before/after: If they only become activated when edited (good, thank you for the fix!), I would prefer to either have them blank or giving numbers like the one Paul suggested. If I see a value prefilled, I assume it has an effect on what I get as results!

**Comment by georgbuechner** [comment]
Since commit 584c3ff9b8f3066dbda17e9c88a4a3871fa0f962 the value of the different advanced setting is either default ( "" for author 0/2019 for date etc.) or it keeps the settings the users chose.
