### ISSUE TITLE
Fehlende Säule

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#104]
Herr Borgards, haben Sie eine Säule entfernt? War sehr irritiert, weil deutlich weniger Suchergebnisse gefunden wurden und dann sehe ich, dass nur noch "Geschichte des Tierwissens" existiert. Können Sie kurz bestätigen, dass Sie die Säule entfernt haben und es sich nicht um einen Fehler unsererseits handelt?`

**Comment by ekoehring** [comment]
Zotero zeigt an, dass die Säule "Forschung CLAS" in den Ordner "Geschichte des Tierwissens" verschoben wurde. Ich nehme an, das ist ein Fehler und kann korrigiert werden (Roland?) -- sie ist aber nicht verschwunden, puuuh!

**Comment by ekoehring** [comment]
Es war in der Tat ein Fehler bei der Benutzung von Zotero, die Säule liegt jetzt wieder an der richtigen Stelle, danke fürs Bescheid sagen!
