### ISSUE TITLE
Searching for n-Words

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#105]
Currently searching for two words only allows two words a the moment. Patch for searching n words will be pushed soon.

**Comment by sladen** [comment]
Seems to work:

* https://clas-digital.uni-frankfurt.de/search?q=dog+hund+hoch+wie+var+oken  
"16 Ergebnisse gefunden in 1.172507074s"

**Comment by sladen** [comment]
Appears to have been fixed in https://github.com/ShadowItaly/clas-digital/commit/46256f2689392041c798f8a1e07fb90894c5cfb3 which uses a `for` loop.
