### ISSUE TITLE
Choosing a collection should be implemented in the new search options

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#108]
Of the options covered in the former "advanced" modal, one has not been implemented in the new search options yet: Choose collection ("Säulen"), probably because of the temporal disappearance of the second collection (closed #104 ).

The choice of choosing between collections should be implemented again.

**Comment by georgbuechner** [comment]
I'm already think about a way to implement this nicely. Thanks for mentioning again!

**Comment by sladen** [comment]
Advanced drop-down with:

* All CLAS collections
* History of Animals
* Future of Animals

Where these are sourced automatically from the Zotero metadata (Pillars).

**Comment by georgbuechner** [comment]
This has also been implemented in commit 584c3ff9b8f3066dbda17e9c88a4a3871fa0f962. The Layout is a bit strange. How do I create a select box with the possibilty to select multiple values and have it still be a drop-down? 
Relevant code is in `web/Search.html` line `867`

**Comment by sladen** [comment]
Think the clear, simple user-interface is more important than allowing every possible combination.

Therefore a drop-down (and intuitively mirrors the current selection), and defaults to "**All CLAS collections**" is easier.

The URL encoding can still manually allow eg:

* https://clas-digital.uni-frankfurt.de/search?q=fuchs+und+katz&pillars=RFWJC42V,XCFFDRQC

for those very special, exceptional cases.

**Comment by ekoehring** [comment]
We can rethink that in the future if there are more than two pillars, but for the moment I alsothink that a simple dropdown (All=1,2; 1; 2) is good enough!
