### ISSUE TITLE
Jumping back into searchbar after changing advanced settings

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#110]
For a better workflow the focus should jump back into the searchbar after changing the advanced settings.

**Comment by sladen** [comment]
Please test any proposed solution with pure keyboard input;  eg. `[Tab]`-key, `[Shift]+[Tab]`-key, `[Enter]`, `[Up]`, `[Down]`.

(Automatically re-focusing may interfere with the normal `<form>` workflow).
