### ISSUE TITLE
CSS position; fixed; should be position: fixed;

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#113]
Minor, but throws a CSS error:  `position; fixed;` (semi-colon) should be `position: fixed;` (colon):

* https://github.com/ShadowItaly/clas-digital/blob/cpp/web/GetBooks.html#L795

That side, the use of `position: fixed;` may suggest that better solutions are available.

**Comment by alleonhardt** [comment]
Typo fixed by 9be212e8dc219303a51d202d66a295e042c96887. Regarding the design issue, going to investigate that a bit further
