### ISSUE TITLE
On error, GetBooks page content should remain (not be replaced with "Access Denied!")

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#114]
Temporary errors can occur for all sorts of reasons.  In `GetBooks.html`, an error fetching the `ocr.txt` causes the whole page content to be replaced with:

`document.body.innerHTML = "<center><h1>Access denied!</h1></center>";`

This is unnecessary, confusing, and makes debugging harder.  Ideally keep-it-simple:

"[OCR text could not be loaded]" can be returned at the OCR text that was not fetched.  There is no need to change the URL or the replace the whole document body.

**Comment by sladen** [comment]
Relevant code is at:

* https://github.com/ShadowItaly/clas-digital/blob/cpp/web/GetBooks.html#L458

**Comment by alleonhardt** [comment]
Fixed by commit: https://github.com/ShadowItaly/clas-digital/commit/f9c64e6fb98f355d604a32a96cd8eaa7a81ccd38

**Comment by sladen** [comment]
https://github.com/ShadowItaly/clas-digital/blob/cpp/web/GetBooks.html#601 shows the `document.body.innerHTML = "<center><h1>Access denied!</h1></center>";` still in the source.
