### ISSUE TITLE
GetBooks: presenting foudn hits when fuzzy=true

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#119]
Search for a book and click link. f.e. https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=Hund&scanId=XUA36SSS&fuzzyness=1#page9 observe, that the user see all pages on which the word has been found an a list of matches. Observe that there are double or multiple entries.

**Comment by alleonhardt** [comment]
Cant reproduce this.
