### ISSUE TITLE
Use *.uni-frankfurt.de certifcate for seamless HTTPS/SSL experience

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#12]
The first time a visitor uses the URL at:

* https://www.clas-digital.uni-frankfurt.de/

an error is shown stating that "This Connection is Untrusted", because of two things:

1. The certificate is not trusted because it is self-signed.
2. The certificate expired on 2019-06-19. The current time is 2019-07-18 10:24.

The steps required to dismiss/accept the self-signed certificate and different on each web browser/operating system.  (This makes writing documentation hard).

Ideally the standard `*.uni-frankfurt.de` certificate would be used and kept in-date.

Alternatively, a "Let's Encrypt!" certificate could be used, along with the script to auto-update every 3 months:

* https://letsencrypt.org/

**Comment by georgbuechner** [comment]
The certificate was deposited at the wrong place. We're going to send it today.

**Comment by ShadowItaly** [comment]
This the the request for ssl certificate.

[certificate.zip](https://github.com/ShadowItaly/clas-digital/files/3772130/certificate.zip)

**Comment by georgbuechner** [comment]
Request is send. We are waiting for an answer. We will give hosting a call on monday to double check

**Comment by georgbuechner** [comment]
Hosting@dlist.de was called on the 28th October. They forwarded the request to German science network.

**Comment by alleonhardt** [comment]
No update. Still waiting on the response, maybe calling on monday.

**Comment by sladen** [comment]
Geothe house colours added in https://github.com/ShadowItaly/clas-digital/commit/1d61844cf7247a31021529b54eb74cc4b0ee68e3 and CLAS logo re-coloured to Goethe house colours in bug #67 and bug #75.

**Comment by sladen** [comment]
@ShadowItaly, @georgbuechner, any updates?

**Comment by georgbuechner** [comment]
Last information I got, is that Alex received an email from hosting, saying, that they forwarded our request. This is about two days ago

**Comment by alleonhardt** [comment]
Fixed check site https://clas-digital.uni-frankfurt.de/

**Comment by sladen** [comment]
* https://clas-digital.uni-frankfurt.de/ - works
* https://www.clas-digital.uni-frankfurt.de/ - doesn't work
