### ISSUE TITLE
Does GetBooks work now?

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#121]
Hey on my PC the book view is functional and does look good. I changed a lot in the css and in the javascript to make it look like my version on every pc. So i was curious how it looks for you I am going to upload some images. From how it looks for me:

![screenshot_20191107-174229_1600x900](https://user-images.githubusercontent.com/23172586/68408652-0935fd00-0186-11ea-9719-c57bc7b71dbb.png)

![screenshot_20191107-174308_1600x900](https://user-images.githubusercontent.com/23172586/68408721-25399e80-0186-11ea-9e0d-af3765b18245.png)
![screenshot_20191107-174414_1600x900](https://user-images.githubusercontent.com/23172586/68408778-3da9b900-0186-11ea-9cbc-2f7f3c44ad59.png)
![screenshot_20191107-174458_1600x900](https://user-images.githubusercontent.com/23172586/68408860-5ca84b00-0186-11ea-80d8-930b771ee306.png)

Is it usable is there something still missing?

**Comment by ekoehring** [comment]
Looks like that to me.

Tiny suggestion: rephrase "next search" and make it say "search within this book", otherwise it sounds as if you would start a new search within the whole collection.

Question: Why the double book information in green and then a link to the same information? I do not understand why that link is needed.

**Comment by alleonhardt** [comment]
The suggestion is implemented should be visible on the server already. Added by commit ac02d0e00b5b8204af34ee1373a175f6b74990a9

The double book information is fixed now. ShowMetadata will show now author, date at which the book was published, ISBN if possible and the citation, we can add even more info if needed. The bibliography should just give some more Information about what book is shown at the moment and the Show metadata function should show extended information about that book. Maybe later on a link to the download page or to the bsb.

**Comment by ekoehring** [comment]
Looking good! The scrolling behaviour also is much better and more intuitive.

I am note sure about the use for the Show metadata at this point. At the moment, it basically gives the full set of info that is already shown on the GetBooks page (as it should be!) again, for a second and third time ("citation" and "bibliography"), plus some of it (title, author, year, but not place) a fourth time in individual lines.
I can see that it might be usefull as a feature in the future, a link to BSB sounds more usefull. But for example, you won't have an ISBN for any of the books in the Geschichte des Tierwissens collection, as ISBN was only introduced 1970.
So developing that would not be a priority for me, and probaby a good thing to discuss together to work out what would be usefull for us as users.

**Comment by sladen** [comment]
In the current proposal for the URL clean-up:

* https://github.com/sladen/clas-digital/blob/bc6daaa8464ba397d33bf8906c355afdb879d964/doc/url-schema.txt

there should be some link from `/books/NNN/pages/` (current `GetBooks`) back to the parent `/books/NNN/` (current `GetMetadata`).  Ideas welcome; eg:

1. separate "[Book info]"
2. current "green text" metadata as link
3. abbreviated green text.
4. something else

Have filed issue #123 to at least set the HTML `<title>` to something useful.  In time, the other HTML metadata (like `<meta name="author">`) can be set too.

**Comment by ekoehring** [comment]
Roland Borgards says: Funktioniert bei mir auch, und sieht gut aus!
