### ISSUE TITLE
start search manually on search page

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#125]
While the "search within this book"-field on get books does have a cute little looking glass (Lupe), the main search page again does only search by pressing enter. Is this on purpose? I think it would be necessary to have something to click on on the main search page.

**Comment by georgbuechner** [comment]
Sorry, I think I delete it by accident. It will be back in a few hours. It's in `web/search.html` incase someone else wants to do it. Should be around `searchbtn` or something
