### ISSUE TITLE
Linking to ShowMetadata from results

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#126]
Following up on the discussion on the ShowMetadata function in issue #121:

At the moment, the green text on the search results (which is the bibliography) links not to GetBooks, but to ShowMetadata.
As ShowMetadata does not offer any additional information yet, only redundant information, and I am probably after GetBooks when clicking on a search result anyhow, I think this is not a good solution. (This might be different, when/if we decide to implement more functionality into ShowMetadata, but at the moment I find it highly irritating).

**Comment by georgbuechner** [comment]
This was an idea from Paul which I very much support, as it provides important consistency:
- clicking on blue link leads to `getBooks`
- clicking the green link leads to `getMetadata` 
- books with no ocr do not link to `getBooks`

We are already working on a new presentation of the metadata of the books, which would make the content seen by the users less redundant. (see new design here: https://www.clas-digital.uni-frankfurt.de/ShowMetadata.html?scanId=PZES2R5E) and we are happy for any suggestions. For instance having better information on the ISBN and such. 

I also don't really see why it is irritating. Already the information is not really redundant, as we provide the citation _and_ the bibliography. 

Concluding: in my opinion, it provides consistency with nice rules on where to click to et certain information. I'm happy to discuss further, but I see the idea behind Pauls suggestion to implement it the way it is at the moment.

**Comment by georgbuechner** [comment]
Or do you see the `getMetadata` page as completely irrelevant for all books? If that is so one could just remove that and a book without ocr has no further link anywhere. I would strictly argue against linking a book without ocr to the `getBooks` page as well as linking to to different pages depending on whether books has or has not got an ocr.

**Comment by ekoehring** [comment]
I have discussed it with Paul and I see where you are heading. It is just not here yet, and when I discovered this without introduction, I could not see the use. I am sorry if I came across ignorant, but to give usefull feedback, I need information: It would have helped finding a bug report about it, explaining why this feature is usefull (consistency) and asking for feedback on the layout. I came here looking for a bug report with explanations for introducing this feature, and only as I could not find one, opened one.
 
I am not disencouraging you from woking on it, but at the moment, the page does not have use in itself. I do understand why you need the consistency, but the page GetMetadata should present itself clearly as usefull, as well.

Let me explain my irritation. It is about the content and presentation of the GetMetadata page.
It has a lot of lines, but is not sorted intuitively and the information is redundant (saying the same things up to 4 times). This is confusing to me.

In detail: I can't see any difference between Citation and Bibliography (and the bibliography on the search results page). If you want to give title, author and year in extra lines again, I am wondering why you do not give place as well, thus covering all the information we use for the biliography. Another order (with the full record first, then in little chunks) is more intuitively understandable when looking at it than chunk 1 - full set - chunk 2 - chunk 3 - full set again - chunk 4.

ISBN: books published before 1970 do never have ISBN (unless reprinted later). If there is no ISBN, it would be better to not display a line about ISBN at all, I think. And it also does not seem to work for books with ISBN (see https://www.clas-digital.uni-frankfurt.de/ShowMetadata.html?scanId=ZUVJ5Z2W) Additional problem is that we did not collect the ISBN systematically for the new books (collection Forschung CLAS).

**Comment by georgbuechner** [comment]
Is this more or like what you where aiming for?

**Comment by ekoehring** [comment]
Better!
You can get rid of "short title" (that is nothing stable, but an abbreviation the user can set in zotero).
Would it be possible to only show ISBN and lib.cat. if this field has a value?

**Comment by georgbuechner** [comment]
give me a second...

**Comment by georgbuechner** [comment]
like that?
