### ISSUE TITLE
GetSugg should be /api/v1/suggestions

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#129]
https://www.clas-digital.uni-frankfurt.de/getsugg?q=hund 
should be
https://www.clas-digital.uni-frankfurt.de/api/v1/typeahead/corpus?q=hun 

Following different options may be available in the future:
- https://www.clas-digital.uni-frankfurt.de/api/v1/typeahead/corpus?q=hund (normal search)
- https://www.clas-digital.uni-frankfurt.de/api/v1/typeahead/dictionary?q=hund (normal search)
- https://www.clas-digital.uni-frankfurt.de/api/v1/typeahead/dictionary/de?q=hund (normal search, german) 
- https://www.clas-digital.uni-frankfurt.de/api/v1/typeahead/dictionary/en?q=dog (normal search, english)
- https://www.clas-digital.uni-frankfurt.de/api/v1/typeahead/authors?q=büchner (search authors)

**Comment by sladen** [comment]
Commit/branch ID?
