### ISSUE TITLE
Can't access Server "Unable to connect"

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#136]
Trying to access either http://clas-digital.uni-frankfurt.de:9991/ or http://clas-digital.uni-frankfurt.de/ leads to "Unable to connect -Firefox can’t establish a connection to the server at clas-digital.uni-frankfurt.de." I'm quit sure it is not due to my internet connection and taking a look at the journal server seems to e running. Any one an idea?

**Comment by georgbuechner** [comment]
Same on google Chrome

**Comment by sladen** [comment]
@georgbuechner:  the webserver is not running and `systemctl status nginx.service` shows:

    Nov 13 15:09:47 class-digital nginx[65466]: nginx: [emerg] unknown directive "/atuh_request" in /etc/clas-digital-devel/bin/forbiddenfiles:2
    Nov 13 15:09:47 class-digital nginx[65466]: nginx: configuration file /etc/nginx/nginx.conf test failed
