### ISSUE TITLE
Syncing devlopers version to the stable version

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#139]
We did a lot of development in the last few days, but most of the changes cant be seen on the Stable version meaning most of the changes cant be seen on https://www.clas-digital.uni-frankfurt.de. We would like you to test the developers version before we upload this version to the main url. To test the developers version please visit:
https://www.clas-digital.uni-frankfurt.de:9991/

A few notes on the changes:
### GetBooks
This has been changed a lot. The reason for that is to simplify the code, meaning to improve the stability on old Browsers. Also the new GetBooks shows multiple hits correctly. Showing incomplete books when one is uploading a new book and only inserts a few files. One click select of the bibliography, just try clicking on the bibliography once. A resizable link window, just try to pull down the blue border. The images of ocrs sticking to each to reduce the confusion which ocr corresponds to which image. And the Ocrs and Images sticking to the top of the screen if necessary.

### Search
A button to select all hits, for creating the bibliography. Also simplifying the code to improve stabilty on old browsers. Fixing the chrome bug see #124 . Finding abbrevations of words. For example searching for hund will search for hunde and hundes as well.

### Administration
Removed the "Save changes" Button. Changes are now saved immediately as soon as they are clicked on.

### Upload Books
When uploading a file which already exists, it will show a split screen with the old version of the image and the new version of the image next to each other. The backups of files which are overwritten are saved in https://www.clas-digital.uni-frankfurt.de:9991/books/ITEMKEY/backups . This folder is access right protected meaning only people with Write access can access the backup folder in a book.

### Copyright protection
Copyright protection is now fully implemented by the new design.

https://www.clas-digital.uni-frankfurt.de:9991/books/ Shows an index of all books on the server, one can verify the uploading of books with this site.

https://www.clas-digital.uni-frankfurt.de:9991/books/NAI269W8/ Will list all files we got on the server for this specific book

So please tell us what you think about the developers version and when you agree we would install the new version on the main site.

**Comment by ekoehring** [comment]
a) GetBooks: Much, much better! Really nice. Also works great on my tablet.

b) Search: Nice! I can't see any bugs right now.

c) BookDetails: I am still not happy with the way the information is presented. I suggest the following order:
1) Bibliography [english, not phie]
2) Author
3) Title
4) Place
5) Date
[6) ISBN] --> only showing if an ISBN is part of the data set
[7) in the future: Library catalog link] 

--> You do not need to try to re-invent a library catalogue or zotero here!

d) Information page: this could still do with a little nicer styling than both logo and text centered.

For our meeting tomorrow, I would like to discuss the "invisible" parts of the project as well: documentation, server, maintainability of the codes (consolidate duplicated JS and CSS), to make sure we are at a good place.

**Comment by georgbuechner** [comment]
Thank your for the review. Shall we merge the developer version. And at what time do we meet tomorrow?

**Comment by ekoehring** [comment]
Let's wait with the merge for tomorrow's meeting and RB's feedback.
The big meeting (with RB and me) will start at 13.00, but I believe Paul and you are meeting at 12?

**Comment by ekoehring** [comment]
We would like to present the functionality in the lecture "Büchners Tiere" next tuesday, 14-16. This would mean that the merge should have happened by then. Is that possible?

**Comment by sladen** [comment]
@georgbuechner, @ShadowItaly.  It is 10 days since this issue was opened—to deploy the development version was opened.  Is anything blocking the switch-over?

**Comment by georgbuechner** [comment]
We're merging tonight.

**Comment by alleonhardt** [comment]
### Versions are merged
The tag from this release is: https://github.com/ShadowItaly/clas-digital/releases/tag/stable-20191125

### GetBooks
The page read mode is fully functional and should be quite fast now. Please give some feedback on the icons if possible. There should be a fullscreen option to improve reading quality when reading on a desktop or laptop. The typeahead search in GetBooks finds multiple hits with either "hund fuchs" or "hund+fuchs". The typeahead search will find every result in the books, just scroll to see all results. Dont get confused by the scroll bar, the search loads all hits on the word as soon as the user starts to scroll, so the scroll bar will start to shrink if there are a lot a hits which are not loaded yet.

### Zotero
Zotero will update at 00:59:30 CET probably the server restart will happen then between 1:30 CET and 2:00 CET.
