### ISSUE TITLE
n Ergebnisse gefunden in 0.024503598 should be in english and have unit

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#146]
tiny, but not to be forgotten:
"n Ergebnisse gefunden in $time" should be "n results found in $time sec."

**Comment by alleonhardt** [comment]
Fixed by commit https://github.com/ShadowItaly/clas-digital/commit/ff73065ebb2e46c8f8f179f179c55e4c2ecca1fd, this fix is still only in the developers version, gonna close this as soon as it is in the stable version
