### ISSUE TITLE
Set rel="shortcut icon" link to favicon

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#150]
On 14 January 2020, Google Search rolled out a new search results page layout, which includes the small favicon when linked correctly:

* https://www.google.com/search?q=clas+digital

Google's Webmaster instructions:

* "Define a favicon to show in search results" https://support.google.com/webmasters/answer/9290858

Minimal code required:

```html
  <head>
    …
    <link rel="shortcut icon" href="static/fav/hand-top-right-16+32+48.ico"/>
   …
  </head>
```

**Comment by georgbuechner** [comment]
I inserted the link to the favicon. Quess we'll have to wait a few days, to see if it worked?

**Comment by ekoehring** [comment]
Seems they stopped it already, again:
"As of Friday, Google had removed the favicons from general Google search results in its Chrome browser."
https://www.techcentral.ie/google-decides-to-iterate-on-favicon-search-plan/

**Comment by alleonhardt** [comment]
Doesnt hurt to have the code anyways. Maybe they will implement it once more and it is wont bother the other browsers if we leave the code inside.
