### ISSUE TITLE
../meta should be always available for all books

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#155]
Try to view: https://www.clas-digital.uni-frankfurt.de:9991/books/JVHEBABM/meta/

returns 403 Forbidden.

(All books have metadata, because that comes from Zotero and provides the primary index key).

**Comment by alleonhardt** [comment]
https://www.clas-digital.uni-frankfurt.de:9991/books/2A7S3CVI/ This one does not have a meta folder

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/ce15868e76d14262550a45caf3ac70f028b95332, because nginx protection now works properly
