### ISSUE TITLE
move .../books/ABC123/view to .../books/ABC123/pages

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#157]
Try to view the pages of a random book:  https://www.clas-digital.uni-frankfurt.de:9991/books/22HN55TJ/view/

Here the URL ends with "view"; ideally URL should end with "pages" as this is what is available at that URL.

(Background: "view" is a verb, "pages" are what are shown (the resource) seen when visiting the URL).

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/ce15868e76d14262550a45caf3ac70f028b95332
