### ISSUE TITLE
Info-Seite

### ISSUE THREAD

**Issue by rolandborgards** [ShadowItaly/clas-digital#159]
CLAS ist mit einer punktierten Linie unterstrichen, das soll weg.
Die Abstände zwischen den Absätzen kleiner.
Insgesamt ist das ein Text, den man tendenziell auf einem Blick lesen können sollte (ohne dass es zu klein wird).

Der Texte auf der Infoseite: breiter, nicht zentriert.

**Comment by sladen** [comment]
"CLAS" is an abbreviation, so marked up with `<abbr title="Cultural and L..">CLAS</abbr>`; this is to enable computers, speech-readers, and humans (with mouse-hover-over) to know what the abbreviation means.

The standard browser (default) rendering for abbreviations is the dotted line.  This can be overridden, but is then not the default.
