### ISSUE TITLE
Wie viele Bücher mit bsb link liegen auch auf dem Server, bzw. wie viele haben einen link ohne scans zu haben

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#160]

**Comment by georgbuechner** [comment]
Hier is a text-file with all the requested information. Hope that is what you wanted.

[inbsb.txt](https://github.com/ShadowItaly/clas-digital/files/4122884/inbsb.txt)

**Comment by georgbuechner** [comment]
Can you confirm, so we can close the issue?

**Comment by sladen** [comment]
It would be useful to post the code-snippet that generated this text file.

This will allow the command to be re-executed.

**Comment by georgbuechner** [comment]
The command will be re-executed everytime the (developer-) server restarts. The file can be found on the server at the location `/etc/clas-digital-devel/inbsb.txt`.

Anyway, the Code is in `src/books/Bookmanager.cpp` line 29. The function is basically an iteration over a dictionary with all books. The key phrase is `if (book.getMetadata("archiveLocation", "data") != "" && book.getOcr() == false)`
