### ISSUE TITLE
New topnav -> all books/ katalog

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#161]
Change the current view of all books, to make it more human readable. 
So a new link "corpus" or "katalog" will apeare in the topnavbar. You can then select collections, author, or time etc. 

What needs to be achieved? Use case: 
1. Give me a list of all books by [author]
2. Give me a list of all books between [date] and [date]
3. Give me a list of all books
4. Give me a list of all collections

**Comment by sladen** [comment]
Possible solutions to the use-cases here:

1. `/catalogue/author/first+last/` in #164
2. `/search/`-related, but would need an "all" to avoid the current solution for fuzzy searching for `e`
3. `/books/`, when `<li>Author (year). <a href="ABC123/">Title of book</a></li>` is done
4. `/catalogue/collections/`  in #164

**Comment by sladen** [comment]
`/catalogue/` (or `/catalog`, or `/katalog`) can have the following links, all of which can be build from *pre-existing* metadata:

* `/books` ("All books")
* `/catalogue/collections` ("All collections")
* `/catalogue/authors` ("All authors")
* `/catalogue/years/` ("All years")

Other pre-built indexes could be added later;  for example based on the the *content* and a *word-list*, eg. pre-indexing of animals:

* `/catalogue/animals` ("All animals")

**Comment by georgbuechner** [comment]
Is this a dublivate of issue 164?

**Comment by alleonhardt** [comment]
Fixed by catalog implementation see https://github.com/ShadowItaly/clas-digital/commit/48893d9011062b9141a35771ee9b626106e64b49
