### ISSUE TITLE
Testing Book Upload

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#162]
Test the upload functionality and give feedback about the documentation.

**Comment by georgbuechner** [comment]
A few help informations are useful:
1. new format for upload
2. Klick "speicher"

**Comment by ekoehring** [comment]
Feedback to the text and layout (apart from https://github.com/ShadowItaly/clas-digital/issues/222#issuecomment-625263585 which I am still confused about):

1) Vorbereitung: Having this paragraphs is useful the first time, but not afterwards. When uploading a lot, it would be nice not having to scroll down everytime - maybe moving this content to a new window that opens on click if needed? [Usability, low priority]

2) Auswählen: This needs the line "Der Upload beginnt erst, wenn Sie weiter unten auf "Speichern" klicken"

3) Alles korrekt: I do not understand how these are supposed to behave, and when (before clicking on Speichern, or afterwards?), the order of the things is confusing

4) Welches Buch: suggestion: swap 2) und 4)
And: "Book File List Index" and "Book Metadata" are now identical, so this can be made simpler.

5) not tested yet

6) Suggestion: Rename to "start", as I would understand "Speichern" as something I do when everything is done, not as something I need to do to start things getting done

7) not tested yet

Hope this helps!

**Comment by ekoehring** [comment]
I continued testing, this time with FJRBKUD3.

1) On my first try, I got the error message "There are files that already exist, you may select whether to overwrite or not for each file" after each uploaded page, but no dialogue to review  -- and also, I am 100% sure that there havent been pages for that book on the server before. So I think that this message just shows all the time, even if it shouldnt.

2) To allow proper testing, I aborted after ca. 350 pages had been uploaded. (Ok, admittedly, my connection broke). I then tried again with the same book. I gotthis error message again, this time correctly. I also got the dialogue to review each page that already exists. But I encountered two problems:

a) the dialogue to compare the two versions only showed the new version:
![Screenshot from 2020-05-08 14-40-35](https://user-images.githubusercontent.com/40890481/81413593-fb1d6500-9145-11ea-8fc5-4524fa97ee45.png)
I dont know whether this was because the first version got broken by aborting (but it happened with all the pages) or this is a bug.

b) More importantly, the workflow is annoying: each page only starts uploading after i reviewed and chose. So that would mean: 350 times the sequence "click 'compare'" - "click 'replace'" - wait 10 seconds - repeat. A "replace all/keep all" would be needed. And also, do not stop uploading other pages until i have made a decision. I want to start the process, leave it running in the background, and then make necessary decisions in the end, not every 10 seconds...
So I aborted it again, sorry for making a mes of FJRBKUD3!

**Comment by sladen** [comment]
The workflow is upside down:

* https://www.clas-digital.uni-frankfurt.de/books/FJRBKUD3/

represents _the book_.  This book object (specific URL) has to exist (be in Zotero) _first_, prior to being able to upload additional pages.

ie. a book starts off with the metadata already complete, but with zero-or-more OCR texts + zero-or-more pages (page images), each with zero-or-more associated revisions (backup images).

Refreshing `books/FJRBKUD3/` _while logged in_ should show whatever state is on the server at that moment, and it should be possible to refresh/upload new OCRs/page images from that page.

This should remove most/all of the UI and state tracking problems:  The "select" revision can be a radio button list one-per-line.

**Comment by ekoehring** [comment]
(Just for your information, uploaded the rest of FJRBKUD3 in small batches...)

**Comment by georgbuechner** [comment]
So, I removed that one strange part: "Alles korrekt"
I also made all the explanations hidden by default. When clicking on the headline, the explanations expand. All you need to see, for uploading a new book/ pages/ ocr can be seen without any scrolling and you have all necessarily information still visible. 
Have a look on the development server to test this: https://www.clas-digital.uni-frankfurt.de:9991/

**Comment by ekoehring** [comment]
For me, the explanations were open on default. But generally, much better!

**Comment by ekoehring** [comment]
I see that it has now been implemented on the main version, thank you.
