### ISSUE TITLE
Provide catalogue access 

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#164]
After `/books/` listing is complete (machine-readable link to everything), a human readable catalogue can be provided; this tree would be a pre-computed static index:

* `/catalogue/` (list ~3 items)
* `/catalogue/collections/` (list with ~2 items)
* `/catalogue/collections/XCFFDRQC/`  (`data.collections[0]` Zotero primary key)
* `/catalogue/collections/RFWJC42V/`
* `/catalogue/authors/`  (lowercase(`data.creators[0].firstName` + "+" + `data.creators[0].lastName`))
* `/catalogue/authors/georg+buchner/` (avoids `%2C%20` comma-space in URL)
* `/catalogue/years/` (list of all years *actually* in database)
* `/catalogue/years/1810` (`year(data.date)`)

Note that author grouping is only as unique as the combination of `firstName + lastName`; there is insufficient information in Zotero to be more specific; but could be provided externally; with a link to somebody else's unique key(s), ie. GND/VIAF.  Sourcing these require manual matching by an academic expert in the field, and there are often multiples keys for the same author; …or none at all!.  Some quick Javascript for populating a set of possible matches is at

* https://gist.github.com/zuphilip/66699b4515e4d0094f7333240948b108

Optional follow-ups:

1. Other *pre-existing* keys could be used as additional catalogue indexes: eg. `data.place` with the location.
2. The pages could have a static search box with the sub-selection pre-populated to match the subset in that index: eg. only one collection.
3. Dynamic Javascript sorting of the catalogue entries in the page
4. The American `catalog` or German `katalog`, instead of British English `catalogue` could be used to shorten the visible URL.

**Comment by alleonhardt** [comment]
Catalogue is nearly finished now only years are missing. Searching in the catalogue is also possible and was introduced in https://github.com/ShadowItaly/clas-digital/commit/20cbe8cfdfb15e208042e2493e06118def8e59ec

**Comment by alleonhardt** [comment]
Catalogue finished with commit https://github.com/ShadowItaly/clas-digital/commit/aad2a274876d2487160a8f3a5ec57201c7104109

Also changed the url from catalogue to catalog https://github.com/ShadowItaly/clas-digital/commit/48893d9011062b9141a35771ee9b626106e64b49
