### ISSUE TITLE
Move page0*.jpg so access-control for private books works automatically

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#165]
Some books that are still in copyright require access restriction to certain logged in users (see #44).  It should still be possible to access the *metadata* for all books!  (see #156).

The web server handles access control to the content itself, all of which should be under `/books/ABC123/pages/*`.  Therefore, the scans should be moved from `/books/ABC123/page0*.jpg` to `/books/ABC123/pages/page0*.jpg` after #157 is complete.

**Comment by alleonhardt** [comment]
Fixed on the server except for book IXBJWNEJ. This book is corrupted in a way that we have only some jpgs on the server but not all
