### ISSUE TITLE
Site should use HTTPS default port, not redirect to port :1409

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#168]
1. Search for known URLs: https://www.google.com/search?q=site%3Aclas-digital.uni-frankfurt.de
2. Select a page of results from eg.  https://www.clas-digital.uni-frankfurt.de/search?q=katz&start=10
3. Click on a link, eg. https://www.clas-digital.uni-frankfurt.de/GetBooks.html?scanId=A7WZ7WMG
4. Observe redirect to, eg. https://www.clas-digital.uni-frankfurt.de:1409/books/8D38PAMV/pages/?highlight=katz#page174

Ideally the URL should not have ":1409' in the URL.

**Comment by alleonhardt** [comment]
Fixed by commit https://github.com/ShadowItaly/clas-digital/commit/73de58ebc797f8a653fa9a7d47b03078e34acb56, Reason for the error is a bug in nginx when using if in location block https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/. Also added a permanent redirect from :1409 to :443

**Comment by sladen** [comment]
The double-redirect of `GetBooks`→`/pages`→port :1409 is continuing:

```
$ wget --server-response 'https://www.clas-digital.uni-frankfurt.de/GetBooks.html?scanId=QWNUCFC7' -O - 2>&1  | grep -E '(HTTP/1|Location:|GetBooks\.html)' - 
--00:00:00--  https://www.clas-digital.uni-frankfurt.de/GetBooks.html?scanId=QWNUCFC7
 1 HTTP/1.1 301 Moved Permanently
 7 Location: https://www.clas-digital.uni-frankfurt.de/books/QWNUCFC7/pages
Location: https://www.clas-digital.uni-frankfurt.de/books/QWNUCFC7/pages [following]
 1 HTTP/1.1 301 Moved Permanently
 6 Location: https://www.clas-digital.uni-frankfurt.de:1409/books/QWNUCFC7/pages/
Location: https://www.clas-digital.uni-frankfurt.de:1409/books/QWNUCFC7/pages/ [following]
 1 HTTP/1.1 200 OK
```

**Comment by sladen** [comment]
`port_in_redirect off;` is the sledgehammer required.
