### ISSUE TITLE
/pages in-book search should use window.history.pushState() where available to avoid page refresh

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#173]
For the in-book search, standard HTML buttons/submit options should be used so that there is always a just-works fallback.

Where optional Javascript/HTML5 is available then `window.history.pushState()` should be used to push the new URL (with new search term), but without causing a refresh—because `/pages/ABC123/pages` is completely static content, and the refresh gains nothing.

This ensure that URL copy-and-paste works + the browser Back/Forward works; just saving on the page reloads for user-interface speed.

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/5918f84fef943ce5ae117fcc6f9c18597e767586
