### ISSUE TITLE
/pages should provide useful description/metadata

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#186]
Metadata is used by search engines when available.  This can be done for `/pages` by populating `<meta name="description" content="…"/>` with the Bibliography information from the Zotero database.

**Comment by sladen** [comment]
Lost quite a bit of time with confused debugging, because of having set `chattr +i …/forbiddenfiles` for earlier debugging, which causes https://github.com/ShadowItaly/clas-digital/blob/cpp/src/main.cpp#L824 to *silently* fail and never updates the rest.

Anyhow, C++ is quite low-level for HTML output, so needs some HTML escaping function (`&quot;` + `&amp;` + `&lt;` + `&gt;`) to allow populating the `content="…"` *safely*.

**Comment by sladen** [comment]
Lost quite a bit of time with confused debugging, because of having set `chattr +i …/forbiddenfiles` for earlier debugging, which causes https://github.com/ShadowItaly/clas-digital/blob/cpp/src/main.cpp#L824 to *silently* fail and never updates the rest.

Anyhow, C++ is quite low-level for HTML output, so needs some HTML escaping function (`&quot;` + `&amp;` + `&lt;` + `&gt;`) to allow populating the `content="…"` *safely*.

**Comment by alleonhardt** [comment]
This is fixed by https://github.com/ShadowItaly/clas-digital/commit/2618ca7c9574f70f283d7581c833bc5b27b4bc72. Escaping the < and > didnt seem necessary so it was skipped.
