### ISSUE TITLE
catalogue/books: simplify filter feedback/progress hint

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#193]
In: `https://www.clas-digital.u ni-frankfurt.de:9991/catalog ue/books/` the interactive search feedback is given as:

```html
<p id="filteropts" style="display: block; color: grey;">
  Filtering yielded 5 results<br>
  Searched 1234/5249 entries
</p>
```

This should be simplified to something like:

```html
<aside class="feedback">
  <p>
    <label for="filtering">Showing:</label>
    <span id="filtered">5</span>/<progress id="filtering" max="5249" value="1234">1234</progress>
  </p>
</aside>
```

With CSS moved into the `<head><style>` block:

```css
aside.feedback { color: grey; }
```
and Javascript updating via eg.:

```JavaScript
document.getElementById('filtered').value = 5;
```

**Comment by alleonhardt** [comment]
Should be fixed by https://github.com/ShadowItaly/clas-digital/commit/4737d6714467777ea157c9331b882a3d327fbb97. If i missed the point of this issue just reopen.
