### ISSUE TITLE
 books/* Name field should display full name(s) of all author(s)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#198]
Ideally a book overview, such as:

* https://www.clas-digital.uni-frankfurt.de/books/2237RXTD/

should show:

* Author:
** Lévi-Strauss, Claude
** Needham, Rodney

instead of `lévi-strauss` (lower case only, first surname only) which is returned by `getAuthor()` which appears to come from https://github.com/ShadowItaly/clas-digital/blob/cpp/src/books/Book.cpp#L60

**Comment by alleonhardt** [comment]
To fix this one has to extract the raw data from the json we get from zotero. Raw access to the json can be achieved like here: https://github.com/ShadowItaly/clas-digital/blob/cpp/src/util/StaticWebpageCreator.hpp#L232

**Comment by georgbuechner** [comment]
I added a function `std::vector<std::string> CMetadata::getAuthors()` returning a array of author names in the format `lastName, firstName (if exists)` 

I'm just not 100% sure if I know exactly where to include this function. Is it in https://github.com/ShadowItaly/clas-digital/blob/cpp/src/util/StaticWebpageCreator.hpp#L123 ?

**Comment by georgbuechner** [comment]
Okay, I edited the changes in my last commit, not sure if it is working now though, as I'm not 100% sure, when the metadata pages get refreshed.

**Comment by alleonhardt** [comment]
This is fixed.
