### ISSUE TITLE
Link to book pages should only show when the book has pages

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#200]
There is a bug in the `CBook::getHasFiles()` Implementation, it does not work for certain books and does not detect if the book has `ocr/image` files. See also in the previous bug fix ac860d037ed5cbe97301fc806339761de2863167

Example: https://www.clas-digital.uni-frankfurt.de:9991/books/8GSCDFSK/

**Comment by georgbuechner** [comment]
Not sure if I understand this issue right, but as there is already a `bool CBook::getOcr()` function, returning whether book has an ocr or not, the `bool CBook::getHasFiles()` should, in my belive, only return true, when the book has images? 
I think I found the bug, and I'll repare it to return true, if the book has images. Book, I can change it to either ocr or images, or to both ocr and images, but this seems redundant.

**Comment by georgbuechner** [comment]
Also, can someone tell me what the possible endings are, apart from .jpg?

**Comment by georgbuechner** [comment]
Ideally everything should be changed to: `hasOcr()`, `hasImages()` and `hasContent()`
