### ISSUE TITLE
When searching the catalog the number of search results dont match the shown number of results

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#201]
Searching for "wissen" in https://www.clas-digital.uni-frankfurt.de:9991/catalogue/books/, leads to different number of entries shown than being found by the function.

**Comment by georgbuechner** [comment]
Seems to be fixxed: https://www.clas-digital.uni-frankfurt.de:9991/catalogue/books/
Please reopen if bug still exists.
