### ISSUE TITLE
Things to do before next release!

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#207]
- [x] Fixing metadata eg issue #203, #204 
- [x] Fix lying cannonical paths in the headers of the catalogue
- [x] Fix the URLS, as much as possible.

The steps above are all necessary before updating the stable version to the new version this issue should provide means to check the status of these tasks

**Comment by georgbuechner** [comment]
As far as I see the only url-problem is that author names containing white-spaces or inserted into the url.
Suggestion: replace white-spaces with a minus.

**Comment by georgbuechner** [comment]
As the next release is online, we can close this.
