### ISSUE TITLE
Cleaning up directory structure

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#212]
There are some books in the directory structure of the clas digital project which are not tracked by zotero at the moment. So the directory should reflect what books are managed at the moment.

**Comment by georgbuechner** [comment]
We will create a file with all books currently untracked by zotero

**Comment by georgbuechner** [comment]
here also I created a file listing all books (item-keys) from books that are on our hard-disc, but not tracked by zotero. (Neither on the server nor in zotero, but Alex and I are not 100% sure about the latter). We're talking about 685 books, so this is actually quite a lot.
Again the file is attached below and also recreated with every server-start. Location on the server: `/etc/clas-digital-devel/untracked_books.txt`

[untracked_books.txt](https://github.com/ShadowItaly/clas-digital/files/4572426/untracked_books.txt)

**Comment by georgbuechner** [comment]
Move code out of initialize function and into `CBookmanager::writeListOfBooks withBSB`. Also check which of those books maybe even have ocrs. rename  `CBookmanager::writeListOfBooks withBSB` to something more fitting.

**Comment by georgbuechner** [comment]
Move untracked folders/ books to archieve

**Comment by ekoehring** [comment]
> here also I created a file listing all books (item-keys) from books that are on our hard-disc, but not tracked by zotero. (Neither on the server nor in zotero, but Alex and I are not 100% sure about the latter). We're talking about 685 books, so this is actually quite a lot.
> Again the file is attached below and also recreated with every server-start. Location on the server: `/etc/clas-digital-devel/untracked_books.txt`
> 
> [untracked_books.txt](https://github.com/ShadowItaly/clas-digital/files/4572426/untracked_books.txt)

Please re-create in human-readable form (Author/Title) for double-checking that my explanation is true.

**Comment by georgbuechner** [comment]
So here is the more human-radable file: 
[untracked_books.txt](https://github.com/ShadowItaly/clas-digital/files/4592897/untracked_books.txt)

Also the code is sorted and moved outside of the initialize function.

**Comment by ekoehring** [comment]
Ok, did some more checks. These are either books that have been moved to the non-public folder or duplicates that have not been properly deleted in zotero but just deleted from a collection, leaving them in zotero as "unfiled items". meaning: they _are_ still in zotero, but not the folders you are asked to track.
so, if they dont take up much space, maybe dont delete them but move to archive, as discussed, but no need to take actions.

**Comment by georgbuechner** [comment]
Books should be moved to an archive, but this is low priority

**Comment by georgbuechner** [comment]
So in the future all files listed by untracked books will be moved to `web/books/old_zotero`. Also the list will be moved there. So no list means no new untracked_files. In the Folder there are all untracked files + the most reset list. 
I guess most of this isn't even necessary, but to have the folders achieve, might be useful at some point.

**Comment by georgbuechner** [comment]
This is not executed on the development server yet.
