### ISSUE TITLE
Decorate books metadata page with navbar

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#213]
The book metadatapage should also have a navigation bar showing, that you are in the catalogue at the moment and giving you the possibility to go directly to search, information etc.

As far as I can see all pages apart from the book metadatapage have the navbar included.

**Comment by georgbuechner** [comment]
So this is kinda solved. The Topnavbar is also include in all book metadatapages. BUT for some reason the dropdown elements from the catologue field were too big, really no Idea why. As a workaround I overewrote the css styling and changes width to 73% in `web/books/metadata_template`
This is far from optimal, I just couldn't find the error causing this problem, maybe someone else can look into that?

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/04d9bd82ec46e4b6dc6d027ea08f05eae0918fcc. Which only fixes the small bug with the width.
