### ISSUE TITLE
Breadcrumb should be visible on all pages

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#219]
* https://developers.google.com/search/docs/data-types/breadcrumb

Eg.

1. Collections > Authors > Buffon > Allgemeine Historie der Natur… > Pages
2. Collections > Years > 1756 > Allgemeine Historie der Natur… > Pages

Or something.

**Comment by georgbuechner** [comment]
Alex and I were thinkig about using non-dynamicbreadcrumbs, reflected in the nav-bar at the top. The Layout would then look something like this:

[information] [search] [catalogue]  
[information] [search] > Results: Hund [catalogue]
[information] [search] [catalogue] > Authors 
[information] [search] [catalogue] > Authors > Borgards 
[information] [search] [catalogues] > books > E738949E 
[information] [search] [catalogues] > books > E738949E > pages

so the breadcumbs being non-dynamic means, that `[information] [search] [catalogues] > books > E738949E > pages` will always been shown no matter if you came from the search or from the catalogue. I think it is how ever a) much easier to implement and b) show the user how the website is structured. Going back to from where you came will of course still work, using the "back" button from the brwoser

**Comment by georgbuechner** [comment]
@sladen using non-dynamicbreadcrumbs, would however mean specifically not have what you seemed to have desired when creating the issue, as the path to pages would always be the same. What do you think?

**Comment by sladen** [comment]
Static breadcrumbs, giving each (logical) parent/grandparent/great-grandparent.
