### ISSUE TITLE
Catalogue Error: Different Authors with same surname

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#221]
The catalogue is confused if several people have the same surname:

Adams, Carol J (books: 8) https://www.clas-digital.uni-frankfurt.de/catalogue/authors/carol-j-adams/
Adams, Carol J. (books: 8) https://www.clas-digital.uni-frankfurt.de/catalogue/authors/carol-j.-adams/
Adams, Douglas (books: 8) https://www.clas-digital.uni-frankfurt.de/catalogue/authors/douglas-adams/
Adams, Maureen (books: 8) https://www.clas-digital.uni-frankfurt.de/catalogue/authors/maureen-adams/

This is urgent, as I want to instruct PaulM this thursday on merging Carol J Adams and Carol J. Adams, but at the moment, things are not clear as all books of these authors are shown in all these entries. 

Edit: Same is true for other cases of surnames, see: https://www.clas-digital.uni-frankfurt.de/catalogue/authors/barbara-allen/ which mixes books by Mary Allen, Barbara Allen and Colin Allen.

**Comment by georgbuechner** [comment]
I'm also working on it. We're trying to get this fixed, in the next hours.

**Comment by ekoehring** [comment]
Thank you! Knowing roughly when something will be fixed is even more important to me than getting it fixed quickly, as then I can make plans based on that information, which is hard without being able to judge myself how complicated an issue is to fix. So, much appreciated!

**Comment by georgbuechner** [comment]
This should be fixed. It's already online on the development server.

Using the same two examples, it seems like it's working now.

Adams:
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/carol-j-adams/
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/carol-j.-adams/
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/douglas-adams/
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/maureen-adams/

Allen:
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/barbara-allen/
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/colin-allen/
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/mary-allen/

**Comment by ekoehring** [comment]
Thank you, can confirm it is fixed
