### ISSUE TITLE
Synchronising stable version with the developer version

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#223]
We did some major bugfixes in the last commits like fixing up the catalogue and the upload function. Unfortunately we can not easily include the fixing commits in the working stable version. So in order to bring the bugfixes to the stable server we would need to do a full synchronization. It would be good to know if we should include the statistics page in the next update, or if we should leave it out for now.

**Comment by ekoehring** [comment]
Leave it out, please.

**Comment by georgbuechner** [comment]
I'm closing this issue, as we actually already did this.
