### ISSUE TITLE
"There are files that already exist, you may select whether to overwrite or not for each file"

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#230]
The bookuploader still gives me this prompt after each single page I upload, even though they do not already exist (and I also dont get an option to select, accordingly)
![image](https://user-images.githubusercontent.com/40890481/82323249-10ad4d00-99d8-11ea-8df1-d03d54abd46e.png)

**Comment by ekoehring** [comment]
... and when one _does_ upload a file that already exists, the compare dialogue is still not working:
![image](https://user-images.githubusercontent.com/40890481/82335083-1f503000-99e9-11ea-8cb5-3c3f6ebcc3cc.png)
And, as mentioned before, having to do these individually in between each page is non-workable. Either the workflow needs to be turned the other way around, as suggested by sladen, or, as a quicker fix, the selection needs to happen for all files at the end of the process, without tstopping the upload until one makes a decision everytime one is needed - and ideally, a "keep all/replace all" would be needed for situations like this one (connections breaking before upload finishes)

(I am aware that I mentioned these issues before, but I am not clear whether they will be fixed.)

**Comment by alleonhardt** [comment]
This is all fixed on the development server, see https://github.com/ShadowItaly/clas-digital/commit/6e7b3afca59913de51f8a6a69da94a89e6e64401. We will leave this open until the stable server has got the update as well and some tests have been done with it.

**Comment by ekoehring** [comment]
Ok, thanks! Should I test it on the development server? (Will files be "lost" if uploading there? I am trying to keep an overview about what I have uploaded/still need to upload etc.)

When are you planning to implement on the main server? I am currently uploading nearly all the time, should we stop that for you implementing?

Sorry for the "stupid questions", but a clear workflow would be helpful!

**Comment by alleonhardt** [comment]
Sorry the answer comes this late. We are trying to update the "stable server" early next week. I will open an workflow issue on github to discuss the general workflow.

**Comment by ekoehring** [comment]
I still have all the problems on the devlopment server, cant see any difference - what am I doing wrong?
![image](https://user-images.githubusercontent.com/40890481/82759819-f0bec480-9def-11ea-8061-2a4d21722b5d.png)

**Comment by alleonhardt** [comment]
I tried as well and it worked. Maybe you still have a cached version of the site on your computer. If that is the case try to reload the page by pressing Shift and hitting the reload button in the browser. This is how it looks for me:
![Screenshot from 2020-05-24 20-35-09](https://user-images.githubusercontent.com/23172586/82761979-7ba6bb80-9dfe-11ea-98fd-2d840787223d.png)
Notice the timestamp in the first image in the left hand corner. This timestamp shows the date and time the site was last updated, this should be at least sunday the 24 May.
![Screenshot from 2020-05-24 20-38-52](https://user-images.githubusercontent.com/23172586/82761996-a3961f00-9dfe-11ea-880d-e2e30f35d3ab.png)

**Comment by ekoehring** [comment]
Yes, now it works, thank you!
