### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#231]
What's wrong with this book?
https://www.clas-digital.uni-frankfurt.de/books/GQAKRGFU/pages/

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/7224fadf483302364978b7cdc3f3a6881c807592. This patch is on the development server only at the moment but we will try to push it to the stable server early next week

**Comment by alleonhardt** [comment]
The book was forbidden because the server thought the book falls under copyright restrictions since it is written in 1920 and we dont have any other way to determine copyright restrictions at the moment.
