### ISSUE TITLE
General Github Workflow

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#233]
Alex and I have a few thoughts on how our workflow should look like.

1. Someone creates an issue
2. Alex and I will try to fix the issue. 
3. When the problem is fixed, Alex or I will add the tag `fixed on development server` 
4. Then it would be great, if whoever created the issue, can do a few test on the development server, to make sure the issue is really fixed. @ekoehring nothing to worry about when uploading the books. They will never show up on the stable server, but apart from that (and wasting disc space) there should be no problems here. _Please do test uploading on development server, when this was the issue!_
5. When, whoever created the issue can safely say, the issue is fixed, either state this in a comment, or directly close the issue. 

Here the link to the development server: https://www.clas-digital.uni-frankfurt.de:9991/

**Comment by ekoehring** [comment]
Ok, cool, will do!

**Comment by georgbuechner** [comment]
So, as you can see, we have started using Milestones. So when you click on the milestone, all Issues tracked there (open and closed) are going to be included in the next update. If you want an issue you created to definitely be included, then add it to the milestone (very similar to adding a label).
Also all the issues in a milestone already closed are already fixed on the development server.
