### ISSUE TITLE
Remove depricated catalogue data

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#234]
The catalogue does never delete data created. It would be good to delete all data, not reflected zotero from the catalogue. 
This _does not mean_ that old date is really lost, as it only concerns the data of the catalogue, as mentioned in #212 the all old zotero entries will be moved to an archive.

**Comment by georgbuechner** [comment]
Also: should an old copied link, where the metadata has been changed, be changed, so that it now links to the edited metadatapage?

**Comment by sladen** [comment]
A redirect from a duplicate, or a merged ID would require knowing both `old_id` + `merged_id`

The information is not being collected, so it would require manual tracking of merges...

**Comment by ekoehring** [comment]
From my perspective, not necessary. There was a lot of movement as we systematically worked through duplicates, but in the future these will be less frequent anyhow.

**Comment by alleonhardt** [comment]
Adhering to miss koehrings advice we will close this and leave the deprecated data on the disk as it does not take up a lot of space and one cannot access it through the website
