### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#248]
- [x] pages of books that are younger than 100 years are only to be displayed to logged in users.

- [ ] books that are younger than 100 years but have "CLASfrei" in the zotero-field "Rights" should be displayed to non-logged in users as well (terms like "frei" or "none" might come with the import, CLASfrei is something only we would use)

- [x] non-logged in users who open a copyrighted book should get a customized 403 or another way of telling them "This book is protected by copyright."

- [ ] Long term, we can think about snippet-view etc.

**Comment by alleonhardt** [comment]
The book https://www.clas-digital.uni-frankfurt.de:9991/books/GQAKRGFU/pages/ should show the new copyright protected view of a copyright protected book. If it does not show the new view open the browser window in an incognito mode and reload the window.

**Comment by alleonhardt** [comment]
Putting "CLASfrei" in the Rights field should enable the books for non logged in users as well now. This has not been tested but can be tested on the development server. Testing would be appreciated!

**Comment by sladen** [comment]
`wget -S https://www.clas-digital.uni-frankfurt.de:9991/books/GQAKRGFU/pages/`

shows:

` 1 HTTP/1.1 200 OK`

The response should be **401** (Not logged in), **403** (Forbidden) or **451** (unavailable for legal reasons), etc …but *not* **200** (OK).

This is to stop the search engines + browers thinking that "Sorry this book is copyright protected, please login to view this book" *is* the **book contents**.

**Comment by alleonhardt** [comment]
Fixed, response is now 401 while still issuing the site.

**Comment by ekoehring** [comment]
I have created a testbook, with 1982 as year and CLASfrei. 
Item ID is Y8Q82PQG.
I will upload some fictional pages to the development server tomorrow, when the ID has been updated to Zotero, then we can see whether it works.
Leaving that here so I remember to delete the book afterwards from Zotero again!

**Comment by ekoehring** [comment]
Uploaded 3 random pages to the testbook, so tomorrow we will see whether it works.

**Comment by ekoehring** [comment]
...seems to work. Over to you.
