### ISSUE TITLE
Some books found with untracked collections

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#251]
While create the breadcumbs (yes, I'm working on this finally), I found that we have some books with a collections which is neither Forschung Clas, nor Geschichte des Tierwissens. 
One example is: "Hüppauf, Vom Frosch: eine Kulturgeschichte zwischen Tierphilosophie und Ökologie, 2011." With the Collection id: 6Y2YKYZT 
I will try to create a list with all books that seem to have old or untracked collectios.

**Comment by ekoehring** [comment]
I can only find this book in zotero with the item id N8CQW64L, part of the collection "Forschung CLAS". There are currently two other entries of this book (duplicates) in "zotero trash".

**Comment by alleonhardt** [comment]
What Jan meant is that the book Hüppauf, Vom Frosch: eine Kulturgeschichte zwischen Tierphilosophie und Ökologie, 2011. is part of the collection "Forschung CLAS" in CLAS Digital public but also part of the collection "Forschung Buechner" in CLAS Digital non public. 

Is this supposed to be? Having books in public and non public collections at the same time? @ekoehring

**Comment by ekoehring** [comment]
Books (with the same zotero id!) can very well be part of several collections. Technically, a book could both be in "Geschichte des Tierwissens" and "Forschung CLAS", with the same Zotero ID, that's how Zotero works. (If if would have two different IDs, then it is one of the duplicates I am hunting down at the moment),

Bu: You should not be bothered (and the project should not make available) anything apart from the two collections "Geschichte des Tierwissens" and "Forschung CLAS". The non public collections are non public!

**Comment by georgbuechner** [comment]
Okay, so if we have a book, which tells us it is alswo in another collection, then this is okay, as long as it is in one of the two collections, which we track? 
If this is the case we can close this issue and no further work is needed.

**Comment by ekoehring** [comment]
Yes. As long as book is in at least one of the tracked collections, all is good. The information that the book is also in other collections should not be displayed on the website (like other information stored in zotero, e.g. "date added").
