### ISSUE TITLE
Book metadata page should always be accessible

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#257]
For unscanned books, the production instance returns `403` when trying to view the metadata ("the book"):

  https://www.clas-digital.uni-frankfurt.de/books/BU3IB2UH/

but on the development server the metadata *is* accessible.

**Comment by alleonhardt** [comment]
Should be fixed by https://github.com/ShadowItaly/clas-digital/commit/91cbc7787ce327c556823679d4faca5e4e549da9 and https://github.com/ShadowItaly/clas-digital/commit/f25b8ae037a5bb3025308765f3831b7464193618

**Comment by alleonhardt** [comment]
The above two commits should fix the problem on the development server, even if they did not intend to fix it.

**Comment by georgbuechner** [comment]
This is fixed?
