### ISSUE TITLE
Zotero metadata - two locations for one book

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#265]
* https://www.clas-digital.uni-frankfurt.de:9991/books/9RCKHPAN/

has:

> Place: München ; New York

Check how this is in the Zotero metadata;  Ideally there would be two items, so that it would be possible to render them as a list (and also for later catalogue indexing on `place=`).

**Comment by ekoehring** [comment]
I appreciate your rigouresness, but that won't work:
There is only one place field (one item), and we made the decision to accept the data in there whatever format. We import from a variety of databases, resulting in a variety of forms there. It is on our lowest priority list to one day go through and style them by hand, we prioritize creating more data and making sure name and title are correct.

However, a catalogue of places would be of NO use for us (reasons being with the way publishing houses are being bought by each other, etc.). So while I can see the system behind catalogueing, this step would create a lot of work for the content team, without _any_ benefit for the human user, so I am strongly opposing it. Will ask RB to also voice an opinion here.

**Comment by georgbuechner** [comment]
Any updates?

**Comment by rolandborgards** [comment]
Ich bin hier ganz Esthers Meinung: NO use for us. Also: nicht tun.

**Comment by sladen** [comment]
Result: `Place=` to be treated as free-form (meaningless) string.
