### ISSUE TITLE
Pages viewer title should be HTML clean (no italics in title)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#268]
Viewing pages of a book:

* https://www.clas-digital.uni-frankfurt.de/books/FJRBKUD3/pages/

shows:

```html
<title>Lenz, <i>Gemeinnützige Naturgeschichte</i>, 1851.</title>
```

This should be just:

```html
<title>Lenz, Gemeinnützige Naturgeschichte, 1851</title>
```

(no italics/bolding inside `<title>…</title>`; and the final `.` (full-stop) is not needed.

**Comment by georgbuechner** [comment]
Fixed with mentioned commit.
