### ISSUE TITLE
Search should (also) match on year

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#269]
Searching for "Lenz 1851", eg:

* https://www.clas-digital.uni-frankfurt.de/search?q=lenz+1851

returns zero results, but would be expected to return these relevant two results:

* https://www.clas-digital.uni-frankfurt.de/books/FJRBKUD3/
* https://www.clas-digital.uni-frankfurt.de/books/A6UWHCUN/

instead of returning zero results.  This should be possible by additionally indexing the year of publication.

**Comment by georgbuechner** [comment]
Sure this is possible, but why not use the advance search for this?

**Comment by sladen** [comment]
It should "just work".

**Comment by georgbuechner** [comment]
Fixed by last commit
