### ISSUE TITLE
[OCR] icon should link directly to …/pages

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#270]
In the catalogue, for example:

* https://www.clas-digital.uni-frankfurt.de/catalogue/authors/harald-othmar-lenz/

some results contain "[OCR]" meaning that the pages have been scanned and are (probably) viewable in the CLAS digital collection.  This "[OCR]" should probably link directly to the book pages view; (and perhaps later by rendered as a book-pages icon).

**Comment by georgbuechner** [comment]
Not sure if it was the best way, to do it, but technically this has been fixed by mentioned commit, for the main catalogue page. Maybe someone can have a look here https://www.clas-digital.uni-frankfurt.de:9991/catalogue/books/ 
If it's okay like this I'll implement it on the other pages too.

**Comment by georgbuechner** [comment]
Server is currently reloading catalogue, so it may take a few minutes, till fix is ready.
