### ISSUE TITLE
New Features Feedback

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#272]
Just went easter egg hunting for new features and found two nice surprises:

- I really like the new pages view, less jumpy and the possibilty to hide the info box is smooth and practical!

- The breadcrumbs obviously still need work in presentation as they take up a lot of space, but they work well and reliably. I can see know how they are usefull not only for machines, but for humans!

Let me know if there is more exciting stuff you want me to have a look at! I am at the moment spending most of my time for the project in zotero, so might not find new features immediately.

Hope everyone got a chance to catch up on sleep :)

**Comment by georgbuechner** [comment]
Thanks a lot for the feedback!  
It definitely was Alex and Paul doing the staying up late yesterday, so thanks a lot from me, for letting me go to sleep earlier!

**Comment by rolandborgards** [comment]
Finde die Infobox jetzt auch sehr gut! Gefällt mir, dass sie jetzt erstmal da ist und dann beiseite geschoben werden kann (funktioniert auch intuitiv sehr gut!).
Kleinigkeit: Man könnte in der Infobx die Info etwas mehr drängen, weniger space, mehr Info. Aber da gibt es bestimmt schon längst ein eigenes issue, sorry for that.
