### ISSUE TITLE
Catalogue authors view, fix </input> closure

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#274]
* https://www.clas-digital.uni-frankfurt.de/catalogue/authors/boria-sax/

Has an unneeded `</input>`:

```html
<input placeholder="Search here..." oninput="on_search(this);"/> </input>
```
the `<input />` is a single node, and has already been closed by the `/>`: this should just be:

```html
<input placeholder="Search here..." oninput="on_search(this);"/>
```

**Comment by georgbuechner** [comment]
Fixed with mentioned commit.
