### ISSUE TITLE
<Magnus> is `<title>` should be escaped:

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#275]
* https://www.clas-digital.uni-frankfurt.de/books/WQ2EGG2X/

has the title `Cod. Pal. germ. 206 Albertus <Magnus>: De animalibus`

The title should be correctly + safely escaped before being inserted into the HTML as `Albertus &lt;Magnus&gt;: De`, and also in the HTML:

```html
<li class="breadcrumb-item active booktitle">
  Cod. Pal. germ. 206 Albertus <Magnus>: De animalibus (Auszüge), dt. ; Glossar (Heidelberg, 1404)
</li>
```

should be:

```html
<li class="breadcrumb-item active booktitle">
  Cod. Pal. germ. 206 Albertus &lt;Magnus&gt;: De animalibus (Auszüge), dt. ; Glossar (Heidelberg, 1404)
</li>
```

**Comment by georgbuechner** [comment]
So I wrote a fix for this, implemnting the function: `func::escapeHTML(string& str)` which currently only escapes `>` and `<` and replaces it with `&lt` and `&gt`. This function is currently _only_ included in `CMetadata::getTitle()`. 
Ideally, when the escaping working well and is a bit more tested. Every function returning anything for the info.json should be going through the escaping. 
Maybe we can track more similar issues in #206 ?

**Comment by georgbuechner** [comment]
This is fixed on the development-server. Shall I leave it open for discussion?

**Comment by ekoehring** [comment]
It was a mistake in the metadata in the first place, fixed there.
