### ISSUE TITLE
Using the new harddisk space

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#278]
We got the new harddisk space of 1TB on the server. The only problem is the harddisk space is installed as a seperate harddisk. In order to use this harddisk space as well we have to use multiple storage locations for the books. We need to figure out a system which writes to the harddisk which is the least used at the moment. This should be implemented as fast as possible in order to use the new space.

**Comment by georgbuechner** [comment]
See also here as a different possibility: 
https://serverfault.com/questions/191299/can-we-mount-multiple-disks-as-one-directory
or https://romanrm.net/mhddfs

**Comment by alleonhardt** [comment]
![Screenshot from 2020-08-10 19-08-34](https://user-images.githubusercontent.com/23172586/89810216-0022f380-db3d-11ea-8bf5-23cdddf6c8fe.png)

Problem is solved using unionfs-fuse to fuse two filesystems at one mount point.

**Comment by sladen** [comment]
An alternative (simpler/more reliable method):

* Production (live) data on one partition
* Development data on second partition

etc.
