### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#282]
At the moment, all searches return 

"The server restarts at the moment please come back in a few minutes!"

see for example https://www.clas-digital.uni-frankfurt.de/search?q=test

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by sladen** [comment]
Searching is broken on the main server; searching is still working on the development server as workaround:

https://www.clas-digital.uni-frankfurt.de:9991/search?q=maus

(Yes, this is the opposite to what should be happening).

**Comment by ekoehring** [comment]
But I think the book collections differs? As workaround, this does not help.

**Comment by georgbuechner** [comment]
We fixed this. Server should be running again. Sorry for the inconvenience. The developmentserver will also be running again soon. 
Please confirm.

**Comment by ekoehring** [comment]
It's working again!
