### ISSUE TITLE
Synchronise page and text view scrolling

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#3]
In the book search view scanned image and OCR appear side by side.

When the user scrolls or searches, the two views get out of step.  For example, if the user scrolls from page 1, down to page 5 in the image scan view, the OCR text will still be at page 1 in the text view.

Ideally, after each scroll-release action, the opposite view should be *scrolled* (not jumped) to "catch up" and remain synchronised.

The #anchor URL should reflect which ever side the last scroll action occurred on (see issue/2).

**Comment by georgbuechner** [comment]
Dublicate of #51
