### ISSUE TITLE
Searching by relevance should be default

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#38]
This is hard at the moment, because loading the matches per page (getPages()) is too slow.

**Comment by ekoehring** [comment]
Maybe I am misunderstanding - but the default setting should be "alphabetically".

**Comment by georgbuechner** [comment]
Sorting by relevance can be set as default. And alphabetical/ cronological order should then be set as options

**Comment by georgbuechner** [comment]
Is default!
