### ISSUE TITLE
Provide 1-page sys-admin documentation (re-install from scratch)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#4]
From time-to-time it will be  necessary to reinstall the whole system on a new clean server (as occurred in 2018 with the move from Wuerzburg to Frankfurt).  Ideally this should be clearly documented, ideally also in script form, exactly how to perform this re-installation, which zero prior knowledge of the system or dependencies.

This sys-admin documentation (except for passwords) should be available directly in the main source code github repository.  This should allow the system to be easily installed on other machines, with other system administrators.

**Comment by georgbuechner** [comment]
Doesn't make sense till interface has been finalized.
