### ISSUE TITLE
Add Info Page with introduction text

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#40]
Change Home to Info

- https://www.clas-digital.uni-frankfurt.de/info

required information: 
- introduction text
- source of the logos
- contact information
- Beta version & where to report bugs
- Uni Frankfurt Logo

**Comment by ekoehring** [comment]
Introduction text attached.
[clas-digital Startseite deutsch_ek.docx](https://github.com/ShadowItaly/clas-digital/files/3707849/clas-digital.Startseite.deutsch_ek.docx)
 Will look  for contact information.

**Comment by sladen** [comment]
(One paragraph in the introduction text got missed; see also bug #57).

**Comment by georgbuechner** [comment]
Can this Issue be closed?

**Comment by ekoehring** [comment]
Yes, opened  #78 for the remaining tiny task (change email adresses to dedicated adresses). We will let you know there when we have them so that this change can be made.
