### ISSUE TITLE
Search: Modal is scrollable but it should no be

### ISSUE THREAD

**Issue by ShadowItaly** [ShadowItaly/clas-digital#45]
Reproduce: Click on the page https://www.clas-digital.uni-frankfurt.de/search and click on the advanced button. The modal is scrollable but it shouldnt be.

**Comment by sladen** [comment]
Will be superseded when issue #109 is done, and "Advanced" button/modal pop-up disappears completely.

**Comment by sladen** [comment]
Superseded by https://github.com/ShadowItaly/clas-digital/commit/e0807f90d6a05af0df3e9b21d8a232defd3ab84e closing bug #109.  …no more Modal "Advanced", for the moment!  Replaced with drop-downs per design in bug #77.
