### ISSUE TITLE
synchronize scrolling

### ISSUE THREAD

**Issue by rolandborgards** [ShadowItaly/clas-digital#48]
Das hatte wir schon mal am Laufen: Wenn man sich einen Treffer anschaut, dann sollte beim links scrollen automatisch rechts mitbewegt werden, und auch wenn man rechts scrollt, sollte links sich automatisch mitbewegen.

**Comment by ShadowItaly** [comment]
Hängt mit diesem Problem zusammen und sollte gleichzeitig gelöst sein.  #51
