### ISSUE TITLE
Filter Results does not always work

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#49]
Die Suche nach "eule" bringt 100 Ergebnisse. Wenn ich die Filteroption "show only boooks with OCR" auswähle, bleiben 98 übrig. Alles gut.

Aber: Die Suche nach "trickster" bringt 2 Ergebnisse, beide "book not scanned yet". Wenn ich die Filteroption "show only boooks with OCR" auswähle, bleiben beide Einträge sichtbar. Bug.

**Comment by ekoehring** [comment]
Just to confirm: issue seems to be solved

**Comment by georgbuechner** [comment]
Right now, the search by relevance is in wrong order. Will be fixxed with next commit! Apart from that, everything should be working at the moment!
