### ISSUE TITLE
Provide 1-page book-uploader documentation (how to upload a book)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#5]
Book scanning, uploading of images, and entering or meta-data are likely to be tasks performed by multiple people, or frequently new people.  There should be a neat 1-page "Howto" instruction document for the most common case, of how to upload a book scan.  This document should include information about how to continue an upload after changing machine, or after a network connection interruption, or after switching between eg. Wifi/cable.

This document is likely to require some screenshots, and then testing the document with users who have not seen the system before, in order to check that document works and expand/improve any missing details, steps, or unclear wording.

**Comment by georgbuechner** [comment]
Doesn't make sense till interface has been finalized.

**Comment by georgbuechner** [comment]
Instead of creating a user manual I extended the information given directly on the page. During our meeting tomorrow, we can discuss, the information given, which information we should add an d which information should stay directly on the page/ should be exported to a seperated document
