### ISSUE TITLE
GetPreview: Sometimes the server crashes!

### ISSUE THREAD

**Issue by ShadowItaly** [ShadowItaly/clas-digital#50]
Sometimes the server crashes when trying to load a preview for the match:
![Screenshot from 2019-10-16 21-06-12](https://user-images.githubusercontent.com/23172586/66950668-211fd280-f059-11e9-8a50-8fb001f022fc.png)

**Comment by georgbuechner** [comment]
The new Pre-Indexing of the preview solved this problem. Important changes for this are in https://github.com/ShadowItaly/clas-digital/blob/cpp/src/books/Book.cpp. Expecially the functions `createMapPreview' and `getPreviewPosition`.
