### ISSUE TITLE
Synchronize left  right: basic function

### ISSUE THREAD

**Issue by rolandborgards** [ShadowItaly/clas-digital#51]
Hier
https://www.clas-digital.uni-frankfurt.de/GetBooks?query=Fledermaus&scanId=S6TCZ35F&fuzzyness=0#page174
entspricht die linke Seite schon beim Suchen überhaupt nicht der rechten Seite

**Comment by ShadowItaly** [comment]
Momentan wird an einer automatischen synchronisierung von beiden Seiten gearbeitet daher kann es momentan zu Problemen bei der Synchronisierung kommen. Wir arbeiten auf jeden Fall am Problem.

**Comment by georgbuechner** [comment]
To reproduce this on the development branch: https://www.clas-digital.uni-frankfurt.de:1222/GetBooks.html?query=Fledermaus&scanId=S6TCZ35F&fuzzyness=0#page174

**Comment by georgbuechner** [comment]
Should be fixed by Alex's new branch.

**Comment by alleonhardt** [comment]
Should be fixed please confirm: https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=hund&scanId=ZTKRB6UW&fuzzyness=0#page5

**Comment by sladen** [comment]
In theory this has been implemented.  But it's broken on various browsers.  Which is bug #90 (and duplicate bug #103).
