### ISSUE TITLE
RAM Issues: To run a developers and a customers version simultanously

### ISSUE THREAD

**Issue by ShadowItaly** [ShadowItaly/clas-digital#53]
In order to keep the server running while developing a diffrent version of the architecture we need to get more RAM to run the two versions simultaneously. This will prevent the server from being down while developing a new version.

**Comment by georgbuechner** [comment]
We're planning on getting 16 GB RAM in total (+ 12) for the next few months, then we can reduce again. Currently waiting for an answer to the mail, to dubble check, if it is okay to get the extra RAM

**Comment by georgbuechner** [comment]
Here is a list of the prices (Klick: "Preisliste") (+12 GM -> 24€/Month): https://www.rz.uni-frankfurt.de/46035891/Virtuelle_Server
We will order the RAM as soon as we have an answer.

**Comment by ekoehring** [comment]
Please order, we are fine with that.

**Comment by georgbuechner** [comment]
Great, we sent an email and are waiting for an answer.

**Comment by ekoehring** [comment]
Signed contract sent out from our side, 29.10.

**Comment by ekoehring** [comment]
"ab 5.11 class-digital.uni-frankfurt.de unmanaged VM +12GB"!
