### ISSUE TITLE
Loading book: Query string shuould not be empty

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#54]
1. Search for a word (no matter which word, any advanced search options)
2. Klick an any result, from f.e.: https://www.clas-digital.uni-frankfurt.de:1222/search?q=hUND&fuzzyness=0&title_only=false&ocr_only=false&author=&publicatedafter=0&publicatedbefore=2018&sortway=sortbyalphabeticalaz&pillars=XCFFDRQC,RFWJC42V&page=1
3. The Query in the link of the opened book will be "". F.e. https://www.clas-digital.uni-frankfurt.de:1222/GetBooks.html?query=&scanId=8D38PAMV&fuzzyness=1
-> This lead to the ocr not being loaded and no found pages are shown.

**Comment by ShadowItaly** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/765b63c7ac155b12e2e3b7d55cb52e4b514289fc
