### ISSUE TITLE
Home-Seite: email adresses / bug tracker

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#56]
1) On the home page,

"Die Forschungsbibliographie wird ständig erweitert. Hinweise nehmen wir sehr gerne auf, bitte per Mail an jan.dick@bdp.de"

should be replaced by

"Die Forschungsbibliographie wird ständig erweitert. Hinweise nehmen wir sehr gerne auf, bitte per Mail an roland.borgards@lingua.uni-frankfurt.de" [and, hopefully soon, by a dedicated adress we have applied for...]

This is because this asks for _content_ feedback. 

2) There should be an encouragement to report bugs. This can be on the home page as well as (for the moment) on the search page (see bug #41). Suggestion is to both add links to this bugtracker and have an email adress (for the moment, Jan's is fine, but we have applied for a dedicated one as well which canhopefully replace that soon)

**Comment by georgbuechner** [comment]
Commit 10df13a4145fdf2ccf34adf715bd79e9e2bdb5f2 fixxed problem
