### ISSUE TITLE
Home-Seite: parts of text missing

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#57]
With bug #40, we had given the text for the home page. One paragraph of that is missing so far. It can be added in smaller font, but shouldbe there, as of the moment, it is not clear _who_ made this project.

Here is the paragraph again:

Die Texte aus der Geschichte des Tierwissens werden im Zusammenhang mit dem Projekt „Büchners Tiere“ (Roland Borgards) erschlossen; daraus erklärt sich die Beschränkung auf den Zeitraum zwischen 1750 und 1850 und die Konzentration auf deutschsprachige Texte. Das hier zugänglich gemachte Korpus kann für benachbarte Fragen (Schillers Tiere, Tiecks Tiere, die Tiere der Romantik, literarische Tiere im frühen 19. Jahrhundert, Tiere in Goethes Faust, usw.) ohne Einschränkung benutzt werden. Eine Erweiterung des Korpus ist geplant, zunächst bis 1900, dann bis 1950, dann um frühneuzeitliche, mittelalterliche und antike zoologische Texte.

**Comment by sladen** [comment]
Ideally "Roland Borgards" should be an HTML link to:

* https://www.uni-frankfurt.de/69369128/FB_10___NDL___Lehrende___Prof__Dr__Roland_Borgards

**Comment by ShadowItaly** [comment]
Should be fixed by: e367d8ede71cd330d23c54f9334a38ed7523a3c8
Please compare at the address: https://www.clas-digital.uni-frankfurt.de/information/

**Comment by ekoehring** [comment]
No, sorry. There are 3 paragraphs, you have now replaced the first paragraph with the third (which was missing before).

Here they are again:

1 (Currently missing)
Die Cultural and Literary Animal Studies (CLAS) widmen sich unter einer kultur-, literatur- und wissensgeschichtlichen Perspektive dem Fragefeld der Tiere. 
clas digital bietet eine Forschungsbibliographie zu den Cultural and Literary Animal Studies sowie Volltexte aus der Geschichte des Tierwissens, mit Konzentration auf die Naturkunde/Zoologie zwischen 1750 und 1850. 

2 (currently correct)
Die Forschungsbibliographie erschließt die geistes- und kulturwissenschaftliche Tierforschung in ihrer disziplinären Vielfalt, gleichwohl ist sie weder vollständig noch ausgewogen; vielmehr trägt sie deutlich die Spuren ihres Entstehungskontextes, d.h. der Neueren Deutschen Literaturgeschichte.  
Die Forschungsbibliographie wird ständig erweitert. Hinweise nehmen wir sehr gerne auf, bitte per Mail an roland.borgards@lingua.uni-frankfurt.de

3 (currently on top, but should be at the end)
Die Texte aus der Geschichte des Tierwissens werden im Zusammenhang mit dem Projekt „Büchners Tiere“ (Roland Borgards) erschlossen; daraus erklärt sich die Beschränkung auf den Zeitraum zwischen 1750 und 1850 und die Konzentration auf deutschsprachige Texte. Das hier zugänglich gemachte Korpus kann für benachbarte Fragen (Schillers Tiere, Tiecks Tiere, die Tiere der Romantik, literarische Tiere im frühen 19. Jahrhundert, Tiere in Goethes Faust, usw.) ohne Einschränkung benutzt werden. Eine Erweiterung des Korpus ist geplant, zunächst bis 1900, dann bis 1950, dann um frühneuzeitliche, mittelalterliche und antike zoologische Texte.
