### ISSUE TITLE
"Home" should be renamed "Information" + URL renamed

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#58]
Following on from bug #40 and #57:

On the page:

* https://clas-digital.uni-frankfurt.de/

At the top-left "Home" should be renamed to "Information".

This is a link and should be renamed from:

* https://clas-digital.uni-frankfurt.de/guest_index.html

to:

* https://clas-digital.uni-frankfurt.de/information/index.de.html

and a symlink created from:

* `/information/index.de.html` to `/information/index.html`

These changes allow:

1. a clean multi-language URL of  `https://clas-digital.uni-frankfurt.de/information/`
2. adding other languages easily; (eg. English at https://clas-digital.uni-frankfurt.de/information/index.en.html)
3. the main web server can automatically serve the correct version based on the browser language preferences.

**Comment by ShadowItaly** [comment]
Should be fixed by: d97fdfb1b091472a56788c0e4f19f7e0f30a49cc
Please compare under: https://www.clas-digital.uni-frankfurt.de/information/
we dont have an english file yet, so maybe the language support is hard to check...
