### ISSUE TITLE
Searching for several words

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#59]
Currently searching for several words has been removed. How important, how useful is this functions, how useful has this function proved? 

What are realistic search cases? How many words would someone want to search simultaneously?
We don't feel comfortable with allowing to search for more than 2 words at the same time. We could however implement a nice and rather fast implementation to check whether to words occur on the same pages "[word1]+[word2]" or in a range of 200 characters "[words1];[word2]". (first is (obviously faster than 2). What are you preferences? What do you think useful?

**Comment by sladen** [comment]
This can probably be answered by having *hard data*.

Perhaps, over the course of a day, make a note of every time a Google search is made for *a single word* verses a search made for *multiple words* (if so, how many).

**Comment by georgbuechner** [comment]
Working as it should except of two possible major Errors
- in some cases search is corrupted (Probably because of error in preview: https://www.clas-digital.uni-frankfurt.de/search?q=Fuchs%2BHund&fuzzyness=1&page=3&maxresultsperpage=50)
- in some cases server crashes. Wasn't able to reproduce this error, even with same search parameters. 
I'm working on both errors.

**Comment by sladen** [comment]
This crashed it:

* https://clas-digital.uni-frankfurt.de/search?q=hund%2B%C5%BFich  (hund+ſich)

**Comment by georgbuechner** [comment]
As far as I see, server doesn't crash anymore. Only "Currupted Search"

**Comment by georgbuechner** [comment]
Seems to by working again. Please confirm.

**Comment by sladen** [comment]
This crashed it "sich":

https://clas-digital.uni-frankfurt.de/search?q=hund%2Bsich

**Comment by georgbuechner** [comment]
Okay, I'll have a check, why that is. This might have to do with getPreview in src/book/Books.cpp

**Comment by georgbuechner** [comment]
The problem seems to be searching for two words and then searching for one word. Can't figure out why that is. Fix will be out soon, maybe not today though.

**Comment by georgbuechner** [comment]
Seems to be fixed now!
