### ISSUE TITLE
Provide 1-page book-manager documentation (how to upload a higher-quality scan/OCR)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#6]
Over time, the quality of original copies, new scans, or OCR texts can be improved, with new copies being obtained.  To make use of these improved versions requires being upload and replace the scans or metadata in the system.  There should be a 1-page document showing how to:

1. replace a page or pages in an existing book; 
2. completely delete an incorrectly uploaded book;

**Comment by georgbuechner** [comment]
Waiting till implementation done.

**Comment by georgbuechner** [comment]
book manager no longer a feature, thus a user-manual/ documentation no longer needed
