### ISSUE TITLE
502 Bad Gateway should work normally

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#60]
The CLAS-Digital site now uses a front-end webserver, that passes dynamic requests (searches) through to a back-end processes.  When the main site is accessed, for example:

* https://www.clas-digital.uni-frankfurt.de/

but the back-end server is not running (~2 minutes during restart + re-index), then the front-end web server attempts to return a `502 Bad Gateway`.  However the *error handler* page for 502 is not accessible, causing a second error `404 Not Found` *for the first error page*; this is returned as a redirect to:

* https://clas-digital.uni-frankfurt.de/web/custom_error502.html

This redirect means that a simple "Refresh" will not work, further disrupting the user's workflow.

Some solutions to this:

a. the front page/static/information content should be always available and returned directly by the web-server, even if the back-end server is restarting.
b. `502 Bad Gateway` should "just work", and show the `502 Bad Gateway` (ie. should not be overridden; no redirect)

The user + browser can then try again by doing a refresh.

**Comment by ShadowItaly** [comment]
Hey paul i fixed the redirect issue. Now the user can just refresh to see the site being online again and sees a meaningful error messages which tells him to try again. So it would be nice to discuss this issue a bit more.

**Comment by ShadowItaly** [comment]
![Screenshot from 2019-10-26 15-33-42](https://user-images.githubusercontent.com/23172586/67620347-0b9f6b00-f806-11e9-8ea5-f8d01612649c.png)
Reloading takes you straight to the main page

**Comment by sladen** [comment]
2368d8d (502 `custom_error502.html`) + defef8f (tweak to `src/default`)
