### ISSUE TITLE
Sort chronologically and alphabetically not working

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#66]
Search results are reloading, but not correctly.
Example: searching vor "hund", switch to chronologically, switch to alphabetically
(Sorry if this is know already)

**Comment by alleonhardt** [comment]
Fixed by: 3488dcd0ce84f56a7ba2e69e86a40d8dd69ae70c and ff4e8459221af5ff180b7f86234f8317863cfa9a

Compare to https://www.clas-digital.uni-frankfurt.de/search?q=hund&fuzzyness=0&title_only=false&ocr_only=false&author=&publicatedafter=0&publicatedbefore=2018&pillars=XCFFDRQC,RFWJC42V&page=1&f_sort=2
