### ISSUE TITLE
Provide 1-page user-manager documentation (how to add/disable a new user)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#7]
Over time is will be necessary to add, modify or disable users in the system.  There should be a 1-side document containing a howto for how to:

1. add a new user
2. update details of a user (eg. new email address)
3. result a password
3. disable a user how no longer needs to access the system.

This *may* benefit from a limited number screenshots, if the actions cannot be purely described in textual form.

**Comment by georgbuechner** [comment]
Doesn't make sense till interface has been finalized.
