### ISSUE TITLE
Minimum search?q= URLs should work without error

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#72]
Minimal URLs should be allowed; such as:

* https://clas-digital.uni-frankfurt.de/search?q=hund

with all parameters in the URL assumed to be the defaults (ie. fuzzyiness, sort-by).

(See also bug #71 about the returned `200 OK` "Corrupted Search Request!" [error] not having enough information).

**Comment by alleonhardt** [comment]
Fixed by 366542273ffde2e47fa5aa34e2c38cad30195fed and 889f581d158d654882e18e29b85ea7330dc72d4e and 448d2859252f97e58aa9df4347ad29baa878341a
