### ISSUE TITLE
Home page (/) should always load, even with backend crashed/restarting

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#73]
The main top-level home page at:

* https://clas-digital.uni-frankfurt.de/

should always be available (ie. as static content served directly by the webserver), even if the backend search daemon is restarting.  This means that:

1. initial first-use page load is very-fast and can be cached
2. search engines can obtain `favicon.ico`, `robots.txt` and index the top-level of the site
3. information about the Beta status, bug tracker and contact information is always available

(ie. it is okay for the *search results* to fail; but the *search box* should always be available).

**Comment by sladen** [comment]
The top-level `/` is redirected to `/search` in the webbserver configuration at:

https://github.com/ShadowItaly/clas-digital/blob/cpp/src/default#L116

with:

    proxy_redirect 	http://localhost:9000/ http://localhost:9000/search;

This would need removing after the content has been provided statically.

**Comment by sladen** [comment]
Commit d308810 already changed https://github.com/ShadowItaly/clas-digital/blob/cpp/src/default#L55 with:

    +       index Search.html;

so possibly this was already planned to work, but because of the redirect at src/default#L116 is not working—which would make this a *bug* (not working as intended).

**Comment by alleonhardt** [comment]
Probably fixed gonna close this as soon the as commit is online.

**Comment by sladen** [comment]
Think this was *eventually* fixed by mega commit 2de4d4 which commented out `index Search.html` in `src/default` and replaced `index.html` with a symlink.
