### ISSUE TITLE
Tab-Symbol should be changed to clas-digital logo

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#75]
Currently the symbol is a origami bird in pink. That is irritating. The symbol should be changed to blue clas-digital-logo. That would provide constancy.

**Comment by ekoehring** [comment]
I want to suggest using the "Hand" of the Main Logo.

**Comment by sladen** [comment]
`/favicon.ico` is the fallback method and should be in Windows ICON container format (the file can contain multiple different-sized icons, but should contain at least 16x16).  For the more modern method, something like the following huge monster covers most portable devices:
    <head>
      <link rel="shortcut icon" href="example-16.png"/>
      <link rel="apple-touch-icon" href="example-57.png" />
      <link rel="apple-touch-icon" href="example-72.png" sizes="72x72" />
      <link rel="apple-touch-icon" href="example-114.png" sizes="114x114" />
      <link rel="icon" type="image/png" href="example-16.png" sizes="16x16" />
      <link rel="icon" type="image/png" href="example-64.png" sizes="64x64" />
      <link rel="icon image_src" type="image/png" href="example-128.png" sizes="128x128" />
      <link rel="icon" type="image/png" href="example-32.png" sizes="32x32" />
    </head>

**Comment by georgbuechner** [comment]
Tab-Symbol is changed. To see the changes, please press shift while reloading page. What do you think?

**Comment by ekoehring** [comment]
Better! But I think that the hand would work even better (less detail/bigger), plus trasnparent background

**Comment by georgbuechner** [comment]
Oh, sorry, where can I find the hand again? Then I'll change it!
