### ISSUE TITLE
Numbers for next search results running out of page. 

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#76]
https://www.clas-digital.uni-frankfurt.de/search?q=hund&fuzzyness=1&title_only=false&ocr_only=false&author=&publicatedafter=0&publicatedbefore=2018&pillars=XCFFDRQC,RFWJC42V&page=1

**Comment by georgbuechner** [comment]
And also a next button (or hotkey!!) for next 10 search results should be implemented.

**Comment by georgbuechner** [comment]
Is a hotkey something that is wanted?

**Comment by georgbuechner** [comment]
Okay, decided I want hotkey for that :D

**Comment by georgbuechner** [comment]
Okay, Hotkey for next page is ">" hotkey for previous page is "<". We can discuss about other options too.

**Comment by sladen** [comment]
Hotkey is good, but is an advanced option; a big fat thumb-sized "Next" button is still needed.

**Comment by sladen** [comment]
The "hit area" can be increased in by CSS using `padding: 1em; margin: 0em` which moves the surrounding area inside the clickable zone.
