### ISSUE TITLE
Rethink searchoptions/ filterresults

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#77]
Is it necessary, to have the filterresults-option? A clean setup would be to have the different search-options as drop-down-menus beneath the search bar. Also search options would apply for all searchs till reset. What do you think?

**Comment by ekoehring** [comment]
Sorry, I am struggling to understand the question - could you please rephrase/explain/give more context?

**Comment by sladen** [comment]
Is this about the Modal/popup dialogue, that appears after clicking "Advanced…" ?  In the HTML source code starting with `<div class="modal-content">` ?

* https://github.com/ShadowItaly/clas-digital/blob/cpp/web/Search.html#L647

Yes, a switch to drop downs *after* the search has been might be an option.

**Comment by georgbuechner** [comment]
The new  setup would look something like this: 
![new_setup](https://user-images.githubusercontent.com/24663156/67700111-a2f2f280-f9ad-11e9-8600-855353b9ec2b.jpeg)


Also before one has searched. The selected options would stay selected over the time you are searching, until one would reset them. The Advanced-Button would disappear. This would however mean, that the are no more "filter results".

**Comment by ekoehring** [comment]
The reason we seperated into advanced and filter was, if I remember correctly: the search took so long that we only wanted to trigger it when necessary... this seems to not longer be the case, so i would be open to an solution like that and look forward to see more drafts after tomorrow's meeting!

**Comment by georgbuechner** [comment]
I uploaded a first version for the new advanced settings. They stay active till the users goes back to search page. The Collections are currently missing.

**Comment by georgbuechner** [comment]
Please report any bugs. I'll start working on this topic again the following days

**Comment by ekoehring** [comment]
See #101

**Comment by sladen** [comment]
This has been implemented; but is buggy.  Those remaining bugs are covered by issue #101 (After/Before chronological presentation) and issue #91 (accurately mirroring the URL in the drop-downs).
