### ISSUE TITLE
Contact Email should be dedicated adress

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#78]
We are in the process of obtaining a dedicated email adress for the project. When we have it, it should be swapped against RB's adress.

**Comment by sladen** [comment]
Is there an overview timeline;  ie. was requested by person X to person Y on date Z?

**Comment by ekoehring** [comment]
We here means Roland Borgards and me. We will let you know when we have it. This bug was opened as there was a request to cose #40, so I wanted this to not get lost.

**Comment by georgbuechner** [comment]
Great, as soon, as you have the email-adress, we will exchange herr borgards email with the new one!

**Comment by ekoehring** [comment]
RZ says only options are mailinglists. Which is a bit weird, but however.
We have set up two lists:

clas-digital-technik@dlist.server.uni-frankfurt.de is for bug reporting (for people who don have a github account). Currently forwards to the three of you and me.

clas-digital@dlist.server.uni-frankfurt.de is for content related feedback (to replace RB's adress), currently forwarding to RB and me.

**Comment by georgbuechner** [comment]
So the technical-issue address, where should it be placed? On the search page, next to/ beneath the link to github?

**Comment by sladen** [comment]
https://github.com/sladen/clas-digital/blob/master/web/information/index.de.html#L44

**Comment by ekoehring** [comment]
clas-digital@ should go at the position Paul pointed at.
clas-digital-technik@ I would suggest to put next to the link to github, yes. I think it would be an encouragement to report bugs for those who do not have github-accounts and are unlikely to openone just to report one bug.
