### ISSUE TITLE
Server should not crash when page=(N+1)>(results/10)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#79]
The backend server crashes when `page=N` is reached.  where `N+1` is greater than or equal to the number of results divided by 10:

* https://clas-digital.uni-frankfurt.de/search?q=foobar&page=2&fuzzyness=0&title_only=false&ocr_only=false&author=&publicatedafter=0&publicatedbefore=2018&pillars=XCFFDRQC,RFWJC42V

ideally the backend server should:

a. not crash (denial of server opportunity)
b. return a blank page of results.

or (bonus points);

1. correct the URL string to the maximum number of results.
2. return the corrected URL via a `Location:` header

or (easy solution):

* always return the last page of results if `N > max returns  / 10`

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/8fd88e7b9dcb59a402ec1fef89fd36cb8339ee31
