### ISSUE TITLE
Search box should be on front page, and have focus

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#8]
Most existing users opening the site are wishing to perform a search.  Ideally the user should be able to start typing and searching immediately with no further mouse actions.

To speed up this common case the search box should be predominately visible on the front page, in a way that is familiar to users.  For example:

  * https://www.google.com/
  * https://www.bing.com/

both use a centrally-placed search box with an auto-focused cursor that flashes in order to prompt the user to be able to type straight away.  Pressing enter submits the search, and the user is moved on to another page with results relevant to that search:

  * https://www.google.com/search?q=hund
  * http://www.bing.com/search?q=hund

ideally the system should follow this quasi-standard user workflow.

**Comment by ShadowItaly** [comment]
We added support for starting on the search site and the autofocus, changing the search system in a way that the user gets redirected to a page relevant to his search is very hard to implement right now.
