### ISSUE TITLE
"Search only in OCR" should be phrased differently

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#80]
Just an issue with the wording:
"Search only in OCR" ot moved to the "advanced" modal and rephrased on the way...

I think it was "Search only books with OCR" before.
"Search only books that have already been scanned" would also be an option, and would be more consistent to the wording used for the search results ("This book has not been scanned yet")

**Comment by georgbuechner** [comment]
How about: Search only scanned books?
Or more consistent:
only unscanned books
only scanned books

**Comment by sladen** [comment]
Needs a bit more investigation, but probably possibly something like:
1. Search all books
2. Scanned books
3. Books with text

**Comment by georgbuechner** [comment]
without an option for searching only books not yet scanned?

**Comment by georgbuechner** [comment]
Some thinking
1. Search [metadata]
2. Search [metadata + ocr]
3. Search [metadata + images]
4. Search [metadata + images + ocr]

**Comment by ekoehring** [comment]
We had discussed this before: case 2 and 3 do not exist in our data. The only use-case we can think of is people wanting to _only_ get results which also include a "book" (images and OCR), which would be case 4. I do not see how the others would be usefull, which is why we went for a tickbox.

**Comment by georgbuechner** [comment]
That is what I believe is correct to. Even if there where books with scans, but no text, or books with ocr but missing images, the case the user cares about is: can I search the text body of this, or can I search only the metadata. And of course I might want to select, that the results show me _only_ books with text.

Personally, thats why I believe: 
- Show only books with text [ here is a tickbox ]

is the only necessary options, as I don't see, why one should search only the metadata.

**Comment by ekoehring** [comment]
There might be good reasons for a different approach, I just wanted to make sure the wording matches the (current) function.

**Comment by sladen** [comment]
Commit f17a23e1 changes to drop down with:

* Search Everything
* Search only Metadata (`title_only=true`)
* Search only Text (`ocr_only=true`

These are *functional*, but still not correctly mirroring the returned URL per bug #91.
