### ISSUE TITLE
Fuzzyness slider should be a tickbox

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#81]
Another one for the advanced modal: If there are only 2 states of fuzzyness, not 3 like before, the slider does not make sense anymore , and should be replaced by a tickbox.

**Comment by georgbuechner** [comment]
Yes, that is already implemented in my new suggestion for the advanced settings. Im striving to implement all those changes en bloc. See also #77

**Comment by sladen** [comment]
Commit https://github.com/ShadowItaly/clas-digital/commit/f17a23e1b584586f7fb840d23fea212772c7a2ed converted "fuzzyness" to a drop-down with two options: "Exact matches" and "Fuzzy matching".
