### ISSUE TITLE
Use start=/limit= (instead of page=/maxresultsperpage=)

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#89]
The subset of found results is currently displayed using

* `maxresultsperpage=` (number of results to show)
* `page=` (where `page * maxresultsperpage` = offset)

When the number of results is changed (0, vs. 10, vs. 50 vs. all) then the `page=` will change drastically have to be completely recalculated.  An alternative solution could be:

* `offset=` (number of first offset; or `skip=`)
* `limit=` (number to show or `max=`)

This give URLs more like:

* `search?q=hund&offset=20&limit=10`
* `search?q=hund&max=all&skip=0`

and allow an advanced user to directly edit the URL bar;  for example if copy and pasting to a book where 42 results fit per printed page.  The syntax would allow jumping to the end:  `offset=-10&max=10` to show the *last* ten results.

**Comment by sladen** [comment]
Google uses `start=N` and Bing uses `first=N`.

**Comment by alleonhardt** [comment]
We will use `start` & `limit` because zotero works with this layout as well and this will cause minimal confusion

**Comment by georgbuechner** [comment]
I'll implement this with start and limit. Negative values for start will be changed to 0.
