### ISSUE TITLE
Provide consistent CLAS branding on site with dog + hand logo

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#9]
Since 2012, projects under the CLAS (Cultural And Literary Animal Studies) umbrella have used a picture of a dog + hand as branding, published in 1898.  This image is out of copyright and credited as:

* Pierre Hachet-Souplet: *Die Dressur der Thiere mit besonderer Berücksichtigung der Hunde, Affen, Pferde, Elephanten und der wilden Thiere*.  Abb. von Bogaert und Jouard.  Leipzig 1898.

(The book is out-of-copyright and likely to be available in the system, this would provide an excellent example, linking and leading straight into the collection).

As a follow-on bonus project, there may be possibilities to incorporate the "hand" as an icon on a small number of places on the site.

**Comment by georgbuechner** [comment]
Clas branding has been partially implemented. We can't proceed further, till the named book is scanned
