### ISSUE TITLE
GetBooks should scroll + be functional

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#90]
1. View eg. https://clas-digital.uni-frankfurt.de/GetBooks.html?query=hund&scanId=ZTKRB6UW&fuzzyness=0#page149
2. Observe that left-side image loads, but rest of screen is grey with no content or UI widgets
3. Try to scroll on left side
4. Observe that nothing happens

What should happen:

The left-hand-side should scroll, and on the right-hand-side should be the OCR + UI elements.

**Comment by georgbuechner** [comment]
I can't reproduce this error. Left-hand-side is scrolling and the right is too, showing the ocr.

**Comment by ekoehring** [comment]
I also have difficulties:
https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=hund&scanId=8D38PAMV&fuzzyness=0#page102
When scrolling on the left down to page 105, the right does scroll, but in a way that never shows me the second half of page 103 (i first see 102 and beginning of 103, which then directly change to 104 without showig 103 in full/second half of 103)

**Comment by alleonhardt** [comment]
There seems to be a problem with some browses showing GetBooks correctly. We are trying to investigate that a bit further. If something does not work press Shift+F5 and select console to show the debug output in firefox. I have problems with reproducing the second issue on firefox + ubuntu 18.04.

**Comment by ekoehring** [comment]
Also Ubuntu and firefox, but it is not a borwser issue, but ....

I think I worked it out: It is an issue of the zoom level. When I zoom out (smaller text, scan image stays the same), more pages of the ocr are already then when i am zoomed in more (logisch).
The question is when do the ocr-pages "jump"? What I experience is that several OCR-pages are shown at the same time, but the last one (at the bottom) is only shown partially. But when the "signal" to "jump" is given (because I have reached the end of a page when scrolling thorugh the scan), the ocr jumps to the beginning of the next page. So I never get to see the parts of the one ocr-page that is only partially seen under my current zoom level -- unless, of course, i scroll at the ocr "column", not jut the scan "column". 

I am not sure my explanations are clear! I could do screenshots, but they won't show the "jumping"

**Comment by sladen** [comment]
This book is book is pretty good stress test (304 pages, dense text):

* https://clas-digital.uni-frankfurt.de/GetBooks.html?query=es&scanId=SXMDAJ4W

**Comment by sladen** [comment]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  newtab
    GET https://clas-digital.uni-frankfurt.de/GetBooks.html [HTTP/1.1 200 OK 0ms]
    Unrecognized at-rule or error parsing at-rule ‘@import’.  GetBooks.html:21
    Expected ‘:’ but found ‘;’.  Declaration dropped.  GetBooks.html:764:9
    Expected ‘:’ but found ‘;’.  Declaration dropped.  GetBooks.html:764:16
    Error in parsing value for ‘font’.  Declaration dropped.  GetBooks.html:816:11
    GET XHR  https://clas-digital.uni-frankfurt.de/books/ZTKRB6UW/ocr.txt [HTTP/1.1 200 OK 0ms]
    GET XHR https://clas-digital.uni-frankfurt.de/books/ZTKRB6UW/readerInfo.json [HTTP/1.1 200 OK 0ms]
    GET XHR https://clas-digital.uni-frankfurt.de/getmetadata [HTTP/1.1 200 OK 69ms]
    GET XHR https://clas-digital.uni-frankfurt.de/searchinbook [HTTP/1.1 200 OK 70ms] queuePage called for: 0  GetBooks.html:304:3
    loadPage called for: 0  GetBooks.html:327:3
    Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  GetBooks.html
    TypeError: val[0].ondblclick is not a function[Learn More]  GetBooks.html:614:6

**Comment by sladen** [comment]
Returning to this page again:

* https://clas-digital.uni-frankfurt.de/GetBooks.html?scanId=SXMDAJ4W

middle-click scrolling on the right-hand (OCR) side (after the first scroll) is limit to scrolling up and down between pages 82 (not before) and 93 (not after).

Wonder if this is yet another escaping issue (not escape `[<>&"]` into `&lt; &gt; &amp; &quot;` and the use of `innerHTML` instead of `innerText`.

**Comment by alleonhardt** [comment]
Hey Paul from the error log you send I could only extract one "real" error. This one should be fixed by now so could you please try again? Maybe fixed by b26ed8bc7a53c57d5f2ca7f3c814b786ca5b15ce and https://github.com/ShadowItaly/clas-digital/commit/8406c841105cd76a4e2bc3559ceb663fab6a6e03

**Comment by ekoehring** [comment]
Just checked with RB: still no scrolling at all on Macbook.
You can come by and teston his Macbook at 16.00!

**Comment by alleonhardt** [comment]
Please check again, a few more bugfixing css could have fixed it

**Comment by alleonhardt** [comment]
For example here: https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=hund&scanId=36XFP384&fuzzyness=0#page16

**Comment by sladen** [comment]
Commit cdbd44c40 presumably made this work, in particular the overriding of CSS `overflow: scroll/auto/hidden`.

Note that the `GetBooks` viewer now "looks a bit weird", but better to be *functional!*
