### ISSUE TITLE
search result drop downs should mirror URL parameters

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#91]
1. View https://clas-digital.uni-frankfurt.de/search?q=hund&page=1&maxresultsperpage=50
2. Observe that the drop down displays "50", like `maxresultsperpage=50`
3. Select "Sort alpabetically"
4. New URL is https://clas-digital.uni-frankfurt.de/search?q=hund&page=1&maxresultsperpage=50&f_sort=2
4. Observe that number of results drop down shows "10", even though URL shows `maxresultsperpage=50`
5. Observe that sort shows "Sort by relevance" even though `f_sort=2` is set

**Comment by alleonhardt** [comment]
Waiting until Jan fixes #77

**Comment by alleonhardt** [comment]
Fixed by 4e16ab9
