### ISSUE TITLE
Search highlighting should minimise bolded section"

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#96]
1. Search for "hello":
2. https://clas-digital.uni-frankfurt.de/search?q=hello
3. Observe first result (from https://clas-digital.uni-frankfurt.de/GetBooks.html?scanId=PCMJGF7M )
4. Observe the length of the bold section "**iii 766 uell«»«v««> (b> iii 69 r°««u» (b) iii 69 hello»»!» »! (n) iii 515 «»eil »«« (n) iii 515 liu [...]**"
5. Observe that this includes the ellipsis ("**[…]**")

Ideally the bolding should be focused around +/- the word(s) being matched.

**Comment by georgbuechner** [comment]
Omg, nether seen this before. I'll have a look, why that is.

**Comment by georgbuechner** [comment]
Did you find any other example where this is the case? Relevant function is `CBook::getOnePreview()` in `src/books/Book.cpp`. Relevant lines `369 - 378`

**Comment by alleonhardt** [comment]
The markup `<mark>hello</mark>` is correct. But the ocr.txt contains html bold tags e. g. `<b>` which the Browser is displaying as bold text. To fix this, one must escape the html character tags. Probably escaping < and >  and " should be enough.
