### ISSUE TITLE
Snippet results should proper ellipse (…) U+2026 instead of three full-stops

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#97]
1. Search for something (anything)
2. eg. https://clas-digital.uni-frankfurt.de/search?q=katz
3. Observe that the snippet uses the sequence "[...]" (bracket dot dot dot bracket)

Ideally the brackets would be removed and the snippet simplified to just the U+2026 ellipse ("…").

The two relevant lines are at:

  https://github.com/ShadowItaly/clas-digital/blob/cpp/src/books/Book.cpp#372

**Comment by georgbuechner** [comment]
Not sure whether you mean this: https://clas-digital.uni-frankfurt.de/search?q=Hund%2BFuchs&fuzzyness=1&maxresultsperpage=10

**Comment by alleonhardt** [comment]
Fixed by https://github.com/ShadowItaly/clas-digital/commit/452fe7a2ce04f4ad814a18911bd940aa28f21d79
