### ISSUE TITLE
Multiple word matching should work with " " spaces aswell as "+" syntax

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#98]
The multiple word matching requires "foo+bar+moo".  This differs from most other search engines.

Ideally multiple word matching should work with:

* `foo bar moo`
* ` foo bar` (Space before foo)
* ` foo bar `
* `foo     bar` (Two spaces between foo and bar)

This has the bonus of keeping the URL nice looking in the normal (common) case; because in HTTP a ` ` space is encoded in the URL as `+`.  (An actual `+` is encoded as `%2B`).

**Comment by sladen** [comment]
Excellent.  Needs a slight further tweak:

1. Open https://clas-digital.uni-frankfurt.de/search?q=katz+und+maus (spaces encoded as `+`) in URL.
2. Hit `[enter]` to search again.
3. Copy-and-paste new URL
4. Observe that this is now https://clas-digital.uni-frankfurt.de/search?q=katz%20und%20maus (space encoded as `%20`)

**Comment by georgbuechner** [comment]
When I however hit `[enter]`again after step for the url changes back to encoding q=katz und maus
https://clas-digital.uni-frankfurt.de/search?q=katz%20und%20maus And the search gives the expected results. 
Can you confirm?
(I'm implementing search for more than too mores soon)

**Comment by alleonhardt** [comment]
We can confirm that the search results are still the same even if the url is diffrent. but it does not look as nice if you got these %20 in them so we have to fix it in a way that it only shows hund+und+katze.

Fixing whitespaces at the end and at the front and multiple whitespaces in between words still needs doing.
