### ISSUE TITLE
Searching two words doesn't check title yet

### ISSUE THREAD

**Issue by georgbuechner** [ShadowItaly/clas-digital#99]
As the function only checks two same pages for the different books it does not check title yet.

**Comment by sladen** [comment]
A good test case for this:

* https://clas-digital.uni-frankfurt.de/search?q=katz+und+maus (`Katz und Maus`)

which *should* match several documents (not yet scanned) with "Katz und Maus" in the metadata.  Presently none are found/highlighted; except when just one-word is searched for:

* https://clas-digital.uni-frankfurt.de/search?q=katz

**Comment by georgbuechner** [comment]
currently, searching for three words is not implemented, only for two. That might causes this. Let me make sure everything round searching for two words is stable again, then, I'll look into this.

**Comment by georgbuechner** [comment]
This seems to work okay. Only one slighty strange error is still there:
- searching for Hund+Fuchs fuzzyness=true and onlyTitle= true gives 0 results, which seems to becorrect: https://clas-digital.uni-frankfurt.de/search?q=Hund%2BFuchs&fuzzyness=1&title_only=true
- searching for Hund+Fuchs fuzzyness=true and onlyOcr= true gives 136 results, which also seems to be fine: https://clas-digital.uni-frankfurt.de/search?q=Hund%2BFuchs&fuzzyness=1&ocr_only=true&maxresultsperpage=1000000
- However searching for the same in ocr + metadata returns 151 results, which seems odd: https://clas-digital.uni-frankfurt.de/search?q=Hund%2BFuchs&fuzzyness=1

Even though for some results (f.e. https://clas-digital.uni-frankfurt.de/ShowMetadata.html?scanId=G27HH85T) the fuzzy seach might identify the authors name as "Fuchs". This however cand really be the problem, as searching for the author is done in all cases. Can't figure out why this is the case at the moment. But I Think the priority of this problem is not very high. I will however keep it in mind. Relevant parts of code are the search() in Bookmanager.cpp and search() in Seach.cpp. It might also be, thank program falsely calls "onSamePage()" (called by CBookManager::Search()). If that is the case, then also the onSamePage() function in Book.cpp might be causing this error. (All files in src/books/)
